### ISSUE TITLE
小程序需要第三方插件，例如腾讯视频插件支持的无法解包

### ISSUE THREAD

**Issue by xjd1123** [qwerty472123/wxappUnpacker#100]
程序执行命令(可选):

程序执行错误信息(如果反馈是抛出异常的错误，必填):

```
复制到这里
Split app-service.js and make up configs & wxss & wxml & wxs...

D:\Program Files\nodejs\node_global\node_modules\vm2\lib\main.js:218
                        throw this._internal.Decontextify.value(e);
                        ^
vm.js:4
}
^

SyntaxError: Unexpected token }
    at new Script (vm.js:74:7)
    at VMScript.compile (D:\Program Files\nodejs\node_global\node_modules\vm2\lib\main.js:78:20)
    at VM.run (D:\Program Files\nodejs\node_global\node_modules\vm2\lib\main.js:212:52)
    at catchZ (D:\Program Files\nodejs\node_global\node_modules\wuRestoreZ.js:11:5)
    at getZ (D:\Program Files\nodejs\node_global\node_modules\wuRestoreZ.js:216:2)
    at wu.get.code (D:\Program Files\nodejs\node_global\node_modules\wuWxml.js:282:3)
    at ioLimit.runWithCb (D:\Program Files\nodejs\node_global\node_modules\wuLib.js:80:8)
    at agent (D:\Program Files\nodejs\node_global\node_modules\wuLib.js:54:14)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:440:3)

下载地址：[15.zip]https://github.com/qwerty472123/wxappUnpacker/files/2178513/15.zip

**Comment by yorick520** [comment]
我也是这样，同求解决方案

**Comment by qwerty472123** [comment]
似乎与 #99 相同 并未按要求提供样例 故关闭之，请等待 #99 解决
