### ISSUE TITLE
编译E:\wechat-by\wxappUnpacker-master\node_modules\vm2\lib\main.js:210出错

### ISSUE THREAD

**Issue by yorick520** [qwerty472123/wxappUnpacker#101]
{ name: '/page-frame.html', off: 997090, size: 1217932 }
Saving files...
Unpack done.
Split app-service.js and make up configs & wxss & wxml & wxs...

E:\wechat-by\wxappUnpacker-master\node_modules\vm2\lib\main.js:210
                        throw this._internal.Decontextify.value(e);
                        ^
SyntaxError: Unexpected token }
    at VMScript.compile (E:\wechat-by\wxappUnpacker-master\node_modules\vm2\lib
main.js:78:20)
    at VM.run (E:\wechat-by\wxappUnpacker-master\node_modules\vm2\lib\main.js:2
4:52)
    at wu.get.code (E:\wechat-by\wxappUnpacker-master\wuJs.js:28:6)
    at ioLimit.runWithCb (E:\wechat-by\wxappUnpacker-master\wuLib.js:80:8)
    at agent (E:\wechat-by\wxappUnpacker-master\wuLib.js:54:14)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)

[源码地址下载](https://pan.baidu.com/s/12LhnNFbJ3KGG3X0mYRe29A)

求帮忙看下，编译下。

**Comment by yorick520** [comment]
另外这个小程序提供有偿帮助，如果有能解析出的，请联系我，将有酬谢。企鹅4971381

**Comment by qwerty472123** [comment]
这个是包内有插件的原因
与 #73 相同
请等待该issue修复
