### ISSUE TITLE
编译出现ReferenceError: x is not defined

### ISSUE THREAD

**Issue by jiangzeyin** [qwerty472123/wxappUnpacker#103]
程序执行命令
node wuWxapkg.js ./pkg/商店.wxapkg
程序执行错误信息:

```
Split app-service.js and make up configs & wxss & wxml & wxs...
Splitting "E:\微信小程序\wxappUnpacker-master\pkg\商店\app-service.js" done.

E:\微信小程序\wxappUnpacker-master\node_modules\vm2\lib\main.js:210
                        throw this._internal.Decontextify.value(e);
                        ^
ReferenceError: x is not defined
    at vm.js:2263:10
    at Script.runInContext (vm.js:102:20)
    at VM.run (E:\微信小程序\wxappUnpacker-master\node_modules\vm2\lib\main.js:204:72)
    at z (E:\微信小程序\wxappUnpacker-master\wuWxml.js:294:7)
    at z (E:\微信小程序\wxappUnpacker-master\wuRestoreZ.js:216:17)
    at catchZ (E:\微信小程序\wxappUnpacker-master\wuRestoreZ.js:12:2)
    at getZ (E:\微信小程序\wxappUnpacker-master\wuRestoreZ.js:216:2)
    at wu.get.code (E:\微信小程序\wxappUnpacker-master\wuWxml.js:282:3)
    at ioLimit.runWithCb (E:\微信小程序\wxappUnpacker-master\wuLib.js:80:8)
    at agent (E:\微信小程序\wxappUnpacker-master\wuLib.js:54:14)

E:\微信小程序\wxappUnpacker-master>

```

网盘链接:
https://pan.baidu.com/s/1QQBZA9_9_O8pNRCEmLNnzA

**Comment by wangzfire** [comment]
me too，请问后来您解决了吗

**Comment by jiangzeyin** [comment]
没有，看了一下，应该是版本问题

**Comment by wdmzsytl** [comment]
我也出现了这个错误，你解决了吗？

**Comment by qwerty472123** [comment]
抱歉，版本过低不予支持
