### ISSUE TITLE
反编译失败

### ISSUE THREAD

**Issue by SpecsShi** [qwerty472123/wxappUnpacker#104]
程序执行命令(可选):

```
node wuWxapkg.js _-80718195_4.wxapkg
```

程序执行错误信息(如果反馈是抛出异常的错误，必填):

```
internal/modules/cjs/loader.js:550
    throw err;
    ^

Error: Cannot find module 'js-beautify'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/Users/specs/Code/tmp/wxappUnpacker/wuJs.js:4:21)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
```

程序结果错误信息(如果反馈不是抛出异常的错误, 必填, 请尽可能详细描述):

程序包: [网盘](https://pan.baidu.com/s/13xLUdZUdYDk8Gvfmy156nA)

其他附加内容:

v0.6vv_20180125_fbi

**Comment by qwerty472123** [comment]
请尝试安装js-beautify
如果安装失败，请与该项目联系

**Comment by KingAmo** [comment]
我也遇到这个错误了，我安装了js-beautify啊。。楼主怎么解决的呢？

**Comment by SpecsShi** [comment]
@KingAmo 安装完就可以了。。你看下是不是少其他的
