### ISSUE TITLE
反编译失败

### ISSUE THREAD

**Issue by lhz1208** [qwerty472123/wxappUnpacker#105]
报错如下：
Unpack file ../1.wxapkg...

Header info:
  firstMark: 0x9c
  unknownInfo:  909015657
  infoListLength:  1879048192
  dataLength:  0
  lastMark: 0x0
C:\Users\HongZhengLi\Desktop\反编译\wxappUnpacker-master\wuWxapkg.js:20
        if(firstMark!=0xbe||lastMark!=0xed)throw Error("Magic number is not correct!");
                                           ^

Error: Magic number is not correct!
    at header (C:\Users\HongZhengLi\Desktop\反编译\wxappUnpacker-master\wuWxapkg.js:20:43)
    at wu.get.buf (C:\Users\HongZhengLi\Desktop\反编译\wxappUnpacker-master\wuWxapkg.js:108:35)
    at ioLimit.runWithCb (C:\Users\HongZhengLi\Desktop\反编译\wxappUnpacker-master\wuLib.js:80:8)
    at agent (C:\Users\HongZhengLi\Desktop\反编译\wxappUnpacker-master\wuLib.js:54:14)

**Comment by qwerty472123** [comment]
您获取到的似乎不是wxapkg
