### ISSUE TITLE
反编译wxml文件都报错了

### ISSUE THREAD

**Issue by jackzhangsir** [qwerty472123/wxappUnpacker#106]
Decompile ./pages/error/error.wxml...
error on ./pages/error/error.wxml
err:  Error: Empty str in prop
    at wxmlify (F:\360Downloads\pkg\xilitiyu\wuWxml.js:179:47)
    at elemToString (F:\360Downloads\pkg\xilitiyu\wuWxml.js:233:57)
    at doWxml (F:\360Downloads\pkg\xilitiyu\wuWxml.js:250:33)
    at tryWxml (F:\360Downloads\pkg\xilitiyu\wuWxml.js:267:3)
    at z (F:\360Downloads\pkg\xilitiyu\wuWxml.js:311:23)
    at z (F:\360Downloads\pkg\xilitiyu\wuRestoreZ.js:216:17)
    at catchZ (F:\360Downloads\pkg\xilitiyu\wuRestoreZ.js:12:2)
    at getZ (F:\360Downloads\pkg\xilitiyu\wuRestoreZ.js:216:2)
    at wu.get.code (F:\360Downloads\pkg\xilitiyu\wuWxml.js:282:3)
    at ioLimit.runWithCb (F:\360Downloads\pkg\xilitiyu\wuLib.js:80:8)
Decompile ./pages/index/index.wxml...
error on ./pages/index/index.wxml
err:  Error: Empty str in prop
    at wxmlify (F:\360Downloads\pkg\xilitiyu\wuWxml.js:179:47)
    at elemToString (F:\360Downloads\pkg\xilitiyu\wuWxml.js:233:57)
    at elemRecursion (F:\360Downloads\pkg\xilitiyu\wuWxml.js:190:10)
    at elemToString (F:\360Downloads\pkg\xilitiyu\wuWxml.js:224:12)
    at elemRecursion (F:\360Downloads\pkg\xilitiyu\wuWxml.js:190:10)
    at elemToString (F:\360Downloads\pkg\xilitiyu\wuWxml.js:228:35)
    at doWxml (F:\360Downloads\pkg\xilitiyu\wuWxml.js:250:33)
    at tryWxml (F:\360Downloads\pkg\xilitiyu\wuWxml.js:267:3)
    at z (F:\360Downloads\pkg\xilitiyu\wuWxml.js:311:23)
    at z (F:\360Downloads\pkg\xilitiyu\wuRestoreZ.js:216:17)

**Comment by jackzhangsir** [comment]
@qwerty472123 你好大神，能帮忙看下吗？ 在反编译apkg包时，报这个错误，wxml都没有生成

**Comment by qwerty472123** [comment]
请提供样例

**Comment by qwerty472123** [comment]
由于你在另一帖子下似乎已经提供了样本而该样本因版本过低导致本项目不予支持，又本帖为按要求提供样本，故默认导致报错的原因与前述样本相同，不予修复，故关闭本issue
