### ISSUE TITLE
还原Wxml和Wxss文件时报错

### ISSUE THREAD

**Issue by marty0929** [qwerty472123/wxappUnpacker#11]
如题，这次测试的是某东的小程序文件

下面的是我直接实用的wuWxapkg.js命令结尾报错信息
```
{ name: '/pages/search/list/list.html', off: 1569361, size: 318 }
{ name: '/pages/specialpay/qianggou/qianggou.html',
  off: 1569679,
  size: 342 }
{ name: '/app-wxss.js', off: 1570021, size: 1031056 }
{ name: '/page-frame.js', off: 2601077, size: 42 }
Saving files...
Unpack done.
Patch game.json and project.config.json file for running and split game.js...
C:\Users\Administrator\Desktop\wxappUnpacker-master\wuLib.js:43
                if(err)throw Error("Read file error: "+err);
                       ^

Error: Read file error: Error: ENOENT: no such file or directory, open 'C:\Users\Administrator\Desktop\wechartWxapkg\jingdong\game.js'
    at ReadFileContext.fs.readFile [as callback] (C:\Users\Administrator\Desktop\wxappUnpacker-master\wuLib.js:43:16)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
```
然后我又尝试分别去编译，app-config.json  app-service.js 正常，尝试到wuWxss命令时，出现一下错误：

```
C:\Users\Administrator\Desktop\wxappUnpacker-master>node wuWxss.js C:\Users\Administrator\Desktop\wechartWxapkg\jingdong
C:\Users\Administrator\Desktop\wxappUnpacker-master\wuLib.js:43
                if(err)throw Error("Read file error: "+err);
                       ^

Error: Read file error: Error: ENOENT: no such file or directory, open 'C:\Users\Administrator\Desktop\wechartWxapkg\jingdong\page-frame.html'
    at ReadFileContext.fs.readFile [as callback] (C:\Users\Administrator\Desktop\wxappUnpacker-master\wuLib.js:43:16)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
```

**Comment by marty0929** [comment]
[moudong.zip](https://github.com/qwerty472123/wxappUnpacker/files/1843990/moudong.zip)
这个是原包文件

**Comment by qwerty472123** [comment]
已经匹配了这种包格式...
这玩意花样真多
