### ISSUE TITLE
分包没有解析出来 wxml也没有出来

### ISSUE THREAD

**Issue by wuearl** [qwerty472123/wxappUnpacker#110]
(如果你是要反馈 bug, 请按以下格式书写 Issue; 如果你遇到的是 Node.js 使用问题, 请尽可能依赖搜索引擎解决问题; 任何对某类小程序包的适配问题都应提供 wxapkg 程序包，否则直接 Close 处理; 提交前请确认 wxapkg 程序包版本不小于 v0.6vv_20180111_fbi (直接用文本编辑器打开 wxapkg包搜索 v0.6vv 即可查到), 旧版本不提供支持, 相关 Issue 直接 Close 处理。)

程序执行命令(可选):

程序执行错误信息(如果反馈是抛出异常的错误，必填):

```
err:  Error: Unknown init callee gz$gwx_77
    at analyze (E:\sou\wxappUnpacker\wuWxml.js:136:22)
    at doWxml (E:\sou\wxappUnpacker\wuWxml.js:248:2)
    at tryWxml (E:\sou\wxappUnpacker\wuWxml.js:267:3)
    at z (E:\sou\wxappUnpacker\wuWxml.js:311:23)
    at z (E:\sou\wxappUnpacker\wuRestoreZ.js:216:17)
    at catchZ (E:\sou\wxappUnpacker\wuRestoreZ.js:12:2)
    at getZ (E:\sou\wxappUnpacker\wuRestoreZ.js:216:2)
    at wu.get.code (E:\sou\wxappUnpacker\wuWxml.js:282:3)
    at ioLimit.runWithCb (E:\sou\wxappUnpacker\wuLib.js:80:8)
    at agent (E:\sou\wxappUnpacker\wuLib.js:54:14)
```

程序结果错误信息(如果反馈不是抛出异常的错误, 必填, 请尽可能详细描述):

程序包(你所要解压的程序包地址, 可为网盘链接, 也可直接上传[上传前请先打包]. 必填):

其他附加内容:
[renren.zip](https://github.com/qwerty472123/wxappUnpacker/files/2257156/renren.zip)

**Comment by inter18099** [comment]
看其他issue，小程序更新了。

**Comment by wuearl** [comment]
不知道您这边会不会更新下呢

**Comment by qwerty472123** [comment]
目前Master分支的最新提交已经初步兼容新版 请尝试
如需提交关于这一更新的bug请另行开启Issue
关于分包，请耐心等待新的更新或自行手工操作，谢谢
