### ISSUE TITLE
err:  Error: Unknown init callee gz$gwx_9

### ISSUE THREAD

**Issue by liucaihs** [qwerty472123/wxappUnpacker#114]
at wu.get.code (C:\Users\amdin\Documents\wxappUnpacker\wuWxml.js:282:3)
    at ioLimit.runWithCb (C:\Users\amdin\Documents\wxappUnpacker\wuLib.js:80:8)
Decompile ./pages/webview/webview.wxml...
error on ./pages/webview/webview.wxml
err:  Error: Unknown init callee gz$gwx_9
    at Error (native)
    at analyze (C:\Users\amdin\Documents\wxappUnpacker\wuWxml.js:136:22)
    at doWxml (C:\Users\amdin\Documents\wxappUnpacker\wuWxml.js:248:2)
    at tryWxml (C:\Users\amdin\Documents\wxappUnpacker\wuWxml.js:267:3)
    at z (C:\Users\amdin\Documents\wxappUnpacker\wuWxml.js:311:23)
    at z (C:\Users\amdin\Documents\wxappUnpacker\wuRestoreZ.js:216:17)
    at catchZ (C:\Users\amdin\Documents\wxappUnpacker\wuRestoreZ.js:12:2)
    at getZ (C:\Users\amdin\Documents\wxappUnpacker\wuRestoreZ.js:216:2)
    at wu.get.code (C:\Users\amdin\Documents\wxappUnpacker\wuWxml.js:282:3)
    at ioLimit.runWithCb (C:\Users\amdin\Documents\wxappUnpacker\wuLib.js:80:8)
Decompile ./pages/winningrecord/index.wxml...

**Comment by qwerty472123** [comment]
目前Master分支的最新提交已经初步兼容新版 请尝试
如需提交关于这一更新的bug请另行开启Issue
