### ISSUE TITLE
请教：分包无法合并，

### ISSUE THREAD

**Issue by kxy000** [qwerty472123/wxappUnpacker#119]
版本：v0.5vv_20180626_syb_zp

程序执行命令(可选):  Windows系统

两个包

主包：>node wuWxapkg.js quanzi.wxapkg
分包：>node wuWxapkg.js -d -s=quanzi quanzi-1.wxapkg
或          node wuWxapkg.js -d -s=.\quanzi quanzi-1.wxapkg

程序执行错误信息(如果反馈是抛出异常的错误，必填):

```
Error: This package is unrecognizable.
May be this package is a subPackage which should be unpacked with -s=<MainDir>.
Otherwise, please decrypted every type of file by hand.
    at Array.packDone (D:\wamp\www\xiaochengxu\unpack\wuWxapkg.js:104:14)
    at CntEvent.decount (D:\wamp\www\xiaochengxu\unpack\wuLib.js:17:43)
    at ioLimit.runWithCb.err (D:\wamp\www\xiaochengxu\unpack\wuLib.js:73:11)
    at agent (D:\wamp\www\xiaochengxu\unpack\wuLib.js:54:14)
    at FSReqWrap.oncomplete (fs.js:169:20)


```

程序结果错误信息(如果反馈不是抛出异常的错误, 必填, 请尽可能详细描述):

程序包(你所要解压的程序包地址, 可为网盘链接, 也可直接上传[上传前请先打包]. 必填):

[unpack.zip](https://github.com/qwerty472123/wxappUnpacker/files/2286273/unpack.zip)

**Comment by qwerty472123** [comment]
分包的这个命令暂不支持啊
加粗写在readme上了
# 当前功能如下（分包功能尚未完成！）
目前对于子包还是要手工操作
感谢提供样例

**Comment by kxy000** [comment]
感谢回复。谢谢
