### ISSUE TITLE
app-config.json文件解析出错

### ISSUE THREAD

**Issue by marty0929** [qwerty472123/wxappUnpacker#12]
```
Decompile ./pages/projecty_record/projecty_record.wxml...
Decompile success!
Decompile ./pages/search/search.wxml...
Decompile success!
Decompile ./pages/subject/subject.wxml...
Decompile success!
Decompile ./pages/video_detail/video_detail.wxml...
Decompile success!
Guess wxss(first turn)...
C:\Users\Administrator\Desktop\wxappUnpacker-master\wuConfig.js:18
                                for(let e of app.tabBar.list){
                                                        ^

TypeError: Cannot read property 'list' of undefined
    at Array.digestsEvent.add (C:\Users\Administrator\Desktop\wxappUnpacker-master\wuConfig.js:18:29)
    at CntEvent.decount (C:\Users\Administrator\Desktop\wxappUnpacker-master\wuLib.js:17:43)
    at wu.get.data (C:\Users\Administrator\Desktop\wxappUnpacker-master\wuConfig.js:40:19)
    at fs.readFile (C:\Users\Administrator\Desktop\wxappUnpacker-master\wuLib.js:44:8)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
```
![image](https://user-images.githubusercontent.com/5567244/37861552-0690462e-2f77-11e8-909c-183318e3138d.png)

对app-config.json的解析还原如果没有app.json内容，可以init一个空文件的容错机制。

**Comment by marty0929** [comment]
我看wuConfig.js里面这一块是按照tabBar这个作为参考来做的循环，这个是有什么规律的吗？有些是没有tabBar属性的呢

**Comment by marty0929** [comment]
```
if(e.tabBar){
			app={pages:k,window:e.global.window,tabBar:e.tabBar,networkTimeout:e.networkTimeout};
		}else{
			app={pages:k,window:e.global.window,networkTimeout:e.networkTimeout};
		}
		
		if(typeof e.debug!="undefined")app.debug=e.debug;
		for(let a in e.page)wu.save(path.resolve(dir,wu.changeExt(a,".json")),JSON.stringify(e.page[a].window,null,4));
		wu.scanDirByExt(dir,"",li=>{//search all files
			let digests=[],digestsEvent=new wu.CntEvent,rdir=path.resolve(dir);
			function fixDir(dir){return dir.startsWith(rdir)?dir.slice(rdir.length+1):dir;}
			digestsEvent.add(()=>{
				if(app.tabBar){
					for(let e of app.tabBar.list){
						e.pagePath=wu.changeExt(e.pagePath);
						let hash=crypto.createHash("MD5").update(e.iconData,'base64').digest();
						for(let [buf,name] of digests)if(hash.equals(buf)){
							delete e.iconData;
							e.iconPath=fixDir(name).replace(/\\/g,'/');
							break;
						}
						hash=crypto.createHash("MD5").update(e.selectedIconData,'base64').digest();
						for(let [buf,name] of digests)if(hash.equals(buf)){
							delete e.selectedIconData;
							e.selectedIconPath=fixDir(name).replace(/\\/g,'/');
							break;
						}
					}
				}
				
				wu.save(path.resolve(dir,'app.json'),JSON.stringify(app,null,4));
				cb({[configFile]:8});
			});
```

个人改动了一下，运行通过

**Comment by qwerty472123** [comment]
感谢
