### ISSUE TITLE
反编译出错

### ISSUE THREAD

**Issue by abigbone** [qwerty472123/wxappUnpacker#124]
(如果你是要反馈 bug, 请按以下格式书写 Issue; 如果你遇到的是 Node.js 使用问题, 请尽可能依赖搜索引擎解决问题; 任何对某类小程序包的适配问题都应提供 wxapkg 程序包，否则直接 Close 处理; 提交前请确认 wxapkg 程序包版本不小于 v0.6vv_20180111_fbi (直接用文本编辑器打开 wxapkg包搜索 v0.6vv 或 v0.5vv 即可查到，注意版本大小主要比较的是日期), 旧版本不提供支持, 相关 Issue 直接 Close 处理。)

程序执行命令(可选):
D:\xampp\htdocs\wxpx>node wuWxapkg.js  D:\xampp\htdocs\_1123949441_157.wxapkg\_1123949441_157.wxapkg

```
Error: Cannot find module 'escodegen'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (D:\xampp\htdocs\wxpx\wuWxml.js:8:17)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

![image](https://user-images.githubusercontent.com/4329020/44196023-60107a80-a16d-11e8-9ae2-b920e20324ba.png)

**Comment by qwerty472123** [comment]
请安装escodegen
依赖包在更新版本后可能会有更新
请注意README.MD的变动或使用`npm install`
