### ISSUE TITLE
运行wuWxapkg.js解析wxapkg包出错

### ISSUE THREAD

**Issue by zxp01** [qwerty472123/wxappUnpacker#127]
(如果你是要反馈 bug, 请按以下格式书写 Issue; 如果你遇到的是 Node.js 使用问题, 请尽可能依赖搜索引擎解决问题; 任何对某类小程序包的适配问题都应提供 wxapkg 程序包，否则直接 Close 处理; 提交前请确认 wxapkg 程序包版本不小于 v0.6vv_20180111_fbi (直接用文本编辑器打开 wxapkg包搜索 v0.6vv 或 v0.5vv 即可查到，注意版本大小主要比较的是日期), 旧版本不提供支持, 相关 Issue 直接 Close 处理。)

程序执行命令(可选): node wxappUnpacker/wuWxapkg.js lianjia.wxapkg

程序执行错误信息(如果反馈是抛出异常的错误，必填):
Split app-service.js and make up configs & wxss & wxml & wxs...

F:\wxapp\wxappUnpacker\node_modules\vm2\lib\main.js:210
                        throw this._internal.Decontextify.value(e);
                        ^
SyntaxError: Unexpected token }
    at VMScript.compile (F:\wxapp\wxappUnpacker\node_modules\vm2\lib\main.js:78:20)
    at VM.run (F:\wxapp\wxappUnpacker\node_modules\vm2\lib\main.js:204:52)
    at wu.get.code (F:\wxapp\wxappUnpacker\wuJs.js:30:6)
    at ioLimit.runWithCb (F:\wxapp\wxappUnpacker\wuLib.js:80:8)
    at agent (F:\wxapp\wxappUnpacker\wuLib.js:54:14)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)

[lianjia.zip](https://github.com/qwerty472123/wxappUnpacker/files/2295755/lianjia.zip)

```
复制到这里
```

程序结果错误信息(如果反馈不是抛出异常的错误, 必填, 请尽可能详细描述):

程序包(你所要解压的程序包地址, 可为网盘链接, 也可直接上传[上传前请先打包]. 必填):

其他附加内容:

**Comment by jinyuling** [comment]
Error: Cannot find module 'escodegen'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\Administrator\wuWxml.js:8:17)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)


请问这个是什么问题呀？

**Comment by jinyuling** [comment]
C:\Users\Administrator>node .\wuWxapkg.js D:\iptv\iptv.wxapkg
Unpack file D:\iptv\iptv.wxapkg...

Header info:
  firstMark: 0xbe
  unknownInfo:  0
  infoListLength:  349
  dataLength:  3447465
  lastMark: 0xed

File list info:
  fileCount:  13
{ name: '/WAWidget.js', off: 363, size: 143590 }
{ name: '/WAWebview.js', off: 143953, size: 755136 }
{ name: '/WAVConsole.js', off: 899089, size: 112067 }
{ name: '/WASubContext.js', off: 1011156, size: 660981 }
{ name: '/WAService.js', off: 1672137, size: 692354 }
{ name: '/WAGameSubContext.js', off: 2364491, size: 194624 }
{ name: '/WAGame.js', off: 2559115, size: 638960 }
{ name: '/WAWorker.js', off: 3198075, size: 106916 }
{ name: '/WASourceMap.js', off: 3304991, size: 21708 }
{ name: '/WAPerf.js', off: 3326699, size: 7454 }
{ name: '/WAGameVConsole.html', off: 3334153, size: 76205 }
{ name: '/WAPageFrame.html', off: 3410358, size: 459 }
{ name: '/WARemoteDebug.js', off: 3410817, size: 37011 }
Saving files...
Unpack done.
C:\Users\Administrator\wuWxapkg.js:104
        }else throw Error("This package is unrecognizable.\nMay be this package is a subPackage which should be unpacked with -s=<MainDir>.\nOtherwise, please decrypted every type of file by hand.")
              ^

Error: This package is unrecognizable.
May be this package is a subPackage which should be unpacked with -s=<MainDir>.
Otherwise, please decrypted every type of file by hand.
    at Array.packDone (C:\Users\Administrator\wuWxapkg.js:104:14)
    at CntEvent.decount (C:\Users\Administrator\wuLib.js:17:43)
    at ioLimit.runWithCb.err (C:\Users\Administrator\wuLib.js:73:11)
    at agent (C:\Users\Administrator\wuLib.js:54:14)
    at FSReqWrap.oncomplete (fs.js:139:20)

C:\Users\Administrator>

**Comment by qwerty472123** [comment]
第一个有插件暂不支持
第二、三个安装相关库
第四个不是存储小程序/小游戏内容的wxapkg包
