### ISSUE TITLE
无法解包

### ISSUE THREAD

**Issue by HoviYan1234** [qwerty472123/wxappUnpacker#130]
node wuWxapkg.js /Users/nali/Downloads/_1345693518_1.wxapkg

/Users/nali/Downloads/wxappUnpacker-master/wuWxapkg.js:10
	let firstMark=buf.readUInt8(0);
	    ^^^^^^^^^
SyntaxError: Unexpected identifier
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
yanhonggui:wxappUnpacker-master nali$

**Comment by qwerty472123** [comment]
请按模板发issue
