### ISSUE TITLE
解包报错

### ISSUE THREAD

**Issue by hiandy168** [qwerty472123/wxappUnpacker#137]
不知道为啥每台电脑都是不行的。

Saving files...
Unpack done.
Split app-service.js and make up configs & wxss & wxml & wxs...

D:\wxappUnpacker-master\node_modules\vm2\lib\main.js:210
                        throw this._internal.Decontextify.value(e);
                        ^
SyntaxError: Illegal return statement
    at VMScript.compile (D:\wxappUnpacker-master\node_modules\vm2\lib\main.js:78:20)
    at VM.run (D:\wxappUnpacker-master\node_modules\vm2\lib\main.js:204:52)
    at z (D:\wxappUnpacker-master\wuWxml.js:365:7)
    at z (D:\wxappUnpacker-master\wuRestoreZ.js:244:17)
    at catchZGroup (D:\wxappUnpacker-master\wuRestoreZ.js:15:2)
    at catchZ (D:\wxappUnpacker-master\wuRestoreZ.js:19:29)
    at getZ (D:\wxappUnpacker-master\wuRestoreZ.js:244:2)
    at wu.get.code (D:\wxappUnpacker-master\wuWxml.js:353:3)
    at ioLimit.runWithCb (D:\wxappUnpacker-master\wuLib.js:80:8)
    at agent (D:\wxappUnpacker-master\wuLib.js:54:14)

D:\wxappUnpacker-master>

**Comment by hiandy168** [comment]
版本：v0.6vv_20180522_fbi
环境：win10 64位 + node v8.11.4

**Comment by qwerty472123** [comment]
v0.6vv_20180522_fbi是含插件的版本 目前不支持
