### ISSUE TITLE
已安装依赖但提示找不到uglify-es

### ISSUE THREAD

**Issue by xibinke** [qwerty472123/wxappUnpacker#138]
这是个bug吗，找不到uglify-es，但这个依赖已经安装过了的。

**程序包版本：**v0.5vv_20180814_syb

**程序执行命令(可选):**
node wuWxapkg.js _-864796962_1.wxapkg

**程序执行错误信息(如果反馈是抛出异常的错误，必填):**

module.js:549
    throw err;
    ^

Error: Cannot find module 'uglify-es'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (d:\wxappUnpacker-master\wuJs.js:3:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**程序结果错误信息(如果反馈不是抛出异常的错误, 必填, 请尽可能详细描述):**

**程序包(你所要解压的程序包地址, 可为网盘链接, 也可直接上传[上传前请先打包]. 必填):**
链接: https://pan.baidu.com/s/16Tzkf4f5GsKpWTbFf5jMTQ 密码: i7xp

**Comment by figure-ai** [comment]
我也是

**Comment by qwerty472123** [comment]
相关问题请咨询uglify-es包的提供者 尝试直接用node是否可以require对应包 搜索百度等
与本项目无关

**Comment by xibinke** [comment]
抱歉，这么久才回复。
问题是我用这里下载的旧版本就没这种问题，现在用的新版就这样。

**Comment by qwerty472123** [comment]
在程序目录下 运行 npm install uglify-es 试试看吧

**Comment by xibinke** [comment]
> 我也是遇到这个问题

这个问题你们解决了吗？

**Comment by xibinke** [comment]
> 我也是


这个问题你们解决了吗？

**Comment by newbie-gadfly** [comment]
npm link uglify-es

**Comment by zhaodexi** [comment]
如楼上，npm link uglify-es一下，其他依赖模块也可能报同样的问题，npm link XX同样处理下。
