### ISSUE TITLE
解压错误

### ISSUE THREAD

**Issue by lhz1208** [qwerty472123/wxappUnpacker#139]
程序执行命令(可选):
node wuWxapkg.js ../1.wxapkg
程序执行错误信息(如果反馈是抛出异常的错误，必填):

```
Split app-service.js and make up configs & wxss & wxml & wxs...
C:\Users\HongZhengLi\Desktop\新しいフォルダー\wxappUnpacker-master\wuLib.js:115
        if(to[0]==".")to=to.slice(1);
             ^

TypeError: Cannot read property '0' of undefined
    at Object.toDir (C:\Users\HongZhengLi\Desktop\新しいフォルダー\wxappUnpacker-master\wuLib.js:115:7)
    at z (C:\Users\HongZhengLi\Desktop\新しいフォルダー\wxappUnpacker-master\wuWxml.js:379:57)
    at z (C:\Users\HongZhengLi\Desktop\新しいフォルダー\wxappUnpacker-master\wuRestoreZ.js:244:17)
    at catchZ (C:\Users\HongZhengLi\Desktop\新しいフォルダー\wxappUnpacker-master\wuRestoreZ.js:28:2)
    at getZ (C:\Users\HongZhengLi\Desktop\新しいフォルダー\wxappUnpacker-master\wuRestoreZ.js:244:2)
    at wu.get.code (C:\Users\HongZhengLi\Desktop\新しいフォルダー\wxappUnpacker-master\wuWxml.js:354:3)
    at ioLimit.runWithCb (C:\Users\HongZhengLi\Desktop\新しいフォルダー\wxappUnpacker-master\wuLib.js:80:8)
    at agent (C:\Users\HongZhengLi\Desktop\新しいフォルダー\wxappUnpacker-master\wuLib.js:54:14)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
```

程序结果错误信息(如果反馈不是抛出异常的错误, 必填, 请尽可能详细描述):

程序包(你所要解压的程序包地址, 可为网盘链接, 也可直接上传[上传前请先打包]. 必填):

其他附加内容:

**Comment by lhz1208** [comment]
[1.zip](https://github.com/qwerty472123/wxappUnpacker/files/2349091/1.zip)

**Comment by qwerty472123** [comment]
文件版本 v0.6vv_20180104_fbi 低于 20180111 本项目就不支持了

**Comment by lhz1208** [comment]
麻烦请教问题：那这个样子的 我需要怎样做 才可以获取出这个代码
