### ISSUE TITLE
4个wxml无法解析，管理员看看是不是bug

### ISSUE THREAD

**Issue by zjjzff1** [qwerty472123/wxappUnpacker#144]
4个wxml无法解析，管理员看看能不能改进
链接：https://pan.baidu.com/s/1UhPIFv1DJq4eDqAtrvdg-Q 密码：byf2

**Comment by qwerty472123** [comment]
问题目前已修复

**Comment by djroad** [comment]
wxml无法解析，管理员请看一下解析的过程
Header info:
  firstMark: 0xbe
  unknownInfo:  0
  infoListLength:  426
  dataLength:  201612
  lastMark: 0xed

File list info:
  fileCount:  13
{ name: '/app-config.json', off: 440, size: 1339 }
{ name: '/app-service.js', off: 1779, size: 113833 }
{ name: '/pages/index.html', off: 115612, size: 872 }
{ name: '/pages/main/about.html', off: 116484, size: 1773 }
{ name: '/pages/main/detail.html', off: 118257, size: 1461 }
{ name: '/pages/main/list.html', off: 119718, size: 1723 }
{ name: '/pages/school.html', off: 121441, size: 2183 }
{ name: '/pages/school/about.html', off: 123624, size: 657 }
{ name: '/pages/school/detail.html', off: 124281, size: 1505 }
{ name: '/pages/school/faq.html', off: 125786, size: 1015 }
{ name: '/pages/school/list.html', off: 126801, size: 1763 }
{ name: '/pages/school/route.html', off: 128564, size: 1266 }
{ name: '/page-frame.html', off: 129830, size: 72222 }
Saving files...
Unpack done.
Split app-service.js and make up configs & wxss & wxml & wxs...
Splitting "/usr/local/nodejs/qudian/app-service.js" done.

/usr/local/nodejs/lib/node_modules/vm2/lib/main.js:210
			throw this._internal.Decontextify.value(e);
			^
SyntaxError: Illegal return statement
    at VMScript.compile (/usr/local/nodejs/lib/node_modules/vm2/lib/main.js:78:20)
    at VM.run (/usr/local/nodejs/lib/node_modules/vm2/lib/main.js:204:52)
    at z (/usr/local/nodejs/wuWxml.js:365:7)
    at z (/usr/local/nodejs/wuRestoreZ.js:244:17)
    at catchZ (/usr/local/nodejs/wuRestoreZ.js:28:2)
    at getZ (/usr/local/nodejs/wuRestoreZ.js:244:2)
    at wu.get.code (/usr/local/nodejs/wuWxml.js:353:3)
    at ioLimit.runWithCb (/usr/local/nodejs/wuLib.js:80:8)
    at agent (/usr/local/nodejs/wuLib.js:54:14)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)

**Comment by yorick520** [comment]
E:\fanbianyi\wxappUnpackermaster>node wuWxml.js E:\fanbianyi\demo\test01\1670088
04475\page-frame.html

E:\fanbianyi\wxappUnpackermaster\node_modules\vm2\lib\main.js:210
                        throw this._internal.Decontextify.value(e);
                        ^
SyntaxError: Illegal return statement
    at VMScript.compile (E:\fanbianyi\wxappUnpackermaster\node_modules\vm2\lib\m
ain.js:78:20)
    at VM.run (E:\fanbianyi\wxappUnpackermaster\node_modules\vm2\lib\main.js:204
:52)
    at z (E:\fanbianyi\wxappUnpackermaster\wuWxml.js:366:7)
    at z (E:\fanbianyi\wxappUnpackermaster\wuRestoreZ.js:244:17)
    at catchZ (E:\fanbianyi\wxappUnpackermaster\wuRestoreZ.js:28:2)
    at getZ (E:\fanbianyi\wxappUnpackermaster\wuRestoreZ.js:244:2)
    at wu.get.code (E:\fanbianyi\wxappUnpackermaster\wuWxml.js:354:3)
    at ioLimit.runWithCb (E:\fanbianyi\wxappUnpackermaster\wuLib.js:80:8)
    at agent (E:\fanbianyi\wxappUnpackermaster\wuLib.js:54:14)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
