### ISSUE TITLE
你好管理，这里是BUG还是包里有框架所导致的？

### ISSUE THREAD

**Issue by djroad** [qwerty472123/wxappUnpacker#149]
你好管理员我的包是 v0.6vv的。这个版本的包应该使用哪一个版本的 wxappUnpacker ？
目前这个包可以解包加分包但是，就是无法解析HTML文件。其他的差不多正常，可不可以帮忙看一下
手动执行过分包，自动执行过分包和解包
程序执行错误信息(如果反馈是抛出异常的错误，必填):

SyntaxError: Illegal return statement
    at VMScript.compile (/usr/local/nodejs/lib/node_modules/vm2/lib/main.js:78:20)
    at VM.run (/usr/local/nodejs/lib/node_modules/vm2/lib/main.js:204:52)
    at wu.get.code (/usr/local/nodejs/wuWxml.js:291:7)
    at fs.readFile (/usr/local/nodejs/wuLib.js:48:8)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)

```

以上这些错误是使用0.2版本的wxappUnpacker造成的，使用的是wuWxml.js 。
```

链接: https://pan.baidu.com/s/172R77SIhNM9QXnbMk1NYTg  提取码: x7av
这是包的地址，麻烦看一下 谢谢。

**Comment by qwerty472123** [comment]
版本过老 不予修复
