### ISSUE TITLE
解压报错，解压出来也没有project.json文件

### ISSUE THREAD

**Issue by qewrifsklrewfafd** [qwerty472123/wxappUnpacker#156]
(如果你是要反馈 bug, 请按以下格式书写 Issue; 如果你遇到的是 Node.js 使用问题, 请尽可能依赖搜索引擎解决问题; 任何对某类小程序包的适配问题都应提供 wxapkg 程序包，否则直接 Close 处理; 提交前请确认 wxapkg 程序包版本不小于 v0.6vv_20180111_fbi (直接用文本编辑器打开 wxapkg包搜索 v0.6vv 或 v0.5vv 即可查到，注意版本大小主要比较的是日期), 旧版本不提供支持, 相关 Issue 直接 Close 处理。)

程序执行命令(可选):
node wuWxapkg.js D:\documents\code\gitlab\小程序源码\pak\_-1923885899_7.wxapkg
程序执行错误信息(如果反馈是抛出异常的错误，必填):

```
D:\documents\code\gitlab\小程序源码\wxappUnpacker\node_modules\vm2\lib\main.js:210
                        throw this._internal.Decontextify.value(e);
                        ^
ReferenceError: _C is not defined
    at vm.js:2:1
    at ContextifyScript.Script.runInContext (vm.js:59:29)
    at VM.run (D:\documents\code\gitlab\小程序源码\wxappUnpacker\node_modules\vm2\lib\main.js:204:72)
    at wu.get.code (D:\documents\code\gitlab\小程序源码\wxappUnpacker\wuWxss.js:160:16)
    at ioLimit.runWithCb (D:\documents\code\gitlab\小程序源码\wxappUnpacker\wuLib.js:80:8)
    at agent (D:\documents\code\gitlab\小程序源码\wxappUnpacker\wuLib.js:54:14)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
```

程序结果错误信息(如果反馈不是抛出异常的错误, 必填, 请尽可能详细描述):

程序包(你所要解压的程序包地址, 可为网盘链接, 也可直接上传[上传前请先打包]. 必填):
链接: https://pan.baidu.com/s/1GwXcUu1jY-bM6_jhMQD4-Q 提取码: hjxn
其他附加内容:

**Comment by qwerty472123** [comment]
版本过低 v0.6vv_20171208_cua_xc
不予支持
请认真阅读issue_template后再发issue

**Comment by qewrifsklrewfafd** [comment]
tks
