### ISSUE TITLE
SyntaxError: Unexpected token }

### ISSUE THREAD

**Issue by HuiNingTech** [qwerty472123/wxappUnpacker#157]
(如果你是要反馈 bug, 请按以下格式书写 Issue; 如果你遇到的是 Node.js 使用问题, 请尽可能依赖搜索引擎解决问题; 任何对某类小程序包的适配问题都应提供 wxapkg 程序包，否则直接 Close 处理; 提交前请确认 wxapkg 程序包版本不小于 v0.6vv_20180111_fbi (直接用文本编辑器打开 wxapkg包搜索 v0.6vv 或 v0.5vv 即可查到，注意版本大小主要比较的是日期), 旧版本不提供支持, 相关 Issue 直接 Close 处理。)

程序执行命令(可选):
node wuWxapkg.js ..\_-925443400_1.wxapkg
程序执行错误信息(如果反馈是抛出异常的错误，必填):

```
  size: 655 }
{ name: '/page-frame.html', off: 1791071, size: 581981 }
Saving files...
Unpack done.
Split app-service.js and make up configs & wxss & wxml & wxs...

C:\Users\Administrator\Desktop\node\node_modules\vm2\lib\main.js:210
                        throw this._internal.Decontextify.value(e);
                        ^
SyntaxError: Unexpected token }
    at VMScript.compile (C:\Users\Administrator\Desktop\node\node_modules\vm2\li
b\main.js:78:20)
    at VM.run (C:\Users\Administrator\Desktop\node\node_modules\vm2\lib\main.js:
204:52)
    at wu.get.code (C:\Users\Administrator\Desktop\node\wuJs.js:30:6)
    at ioLimit.runWithCb (C:\Users\Administrator\Desktop\node\wuLib.js:80:8)
    at agent (C:\Users\Administrator\Desktop\node\wuLib.js:54:14)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)

```

程序结果错误信息(如果反馈不是抛出异常的错误, 必填, 请尽可能详细描述):

编译后文件夹里都是html文件，没有转换为wxml和wxss等。

程序包(你所要解压的程序包地址, 可为网盘链接, 也可直接上传[上传前请先打包]. 必填):
 链接：https://pan.baidu.com/s/1KxTLsNYfqVmPS8Na0M-1xw 密码：fsxx
其他附加内容:
无

**Comment by SpecsShi** [comment]
@qwerty472123 具体是去除哪些呀

**Comment by HuiNingTech** [comment]
@qwerty472123 是呀，怎么去呢
