### ISSUE TITLE
请问还原html为wxml时错误

### ISSUE THREAD

**Issue by yorick520** [qwerty472123/wxappUnpacker#159]
(如果你是要反馈 bug, 请按以下格式书写 Issue; 如果你遇到的是 Node.js 使用问题, 请尽可能依赖搜索引擎解决问题; 任何对某类小程序包的适配问题都应提供 wxapkg 程序包，否则直接 Close 处理; 提交前请确认 wxapkg 程序包版本不小于 v0.6vv_20180111_fbi (直接用文本编辑器打开 wxapkg包搜索 v0.6vv 或 v0.5vv 即可查到，注意版本大小主要比较的是日期), 旧版本不提供支持, 相关 Issue 直接 Close 处理。)

程序执行命令(可选):
 node wuWxml.js -m E:\test01\16\page-frame.html

程序执行错误信息(如果反馈是抛出异常的错误，必填):

```
                        ^
SyntaxError: Illegal return statement
    at VMScript.compile (E:\fanbianyi\wxappUnpacker-master\node_modules\vm2\lib\
main.js:78:20)
    at VM.run (E:\fanbianyi\wxappUnpacker-master\node_modules\vm2\lib\main.js:20
4:52)
    at z (E:\fanbianyi\wxappUnpacker-master\wuWxml.js:366:7)
    at z (E:\fanbianyi\wxappUnpacker-master\wuRestoreZ.js:244:17)
    at catchZGroup (E:\fanbianyi\wxappUnpacker-master\wuRestoreZ.js:15:2)
    at catchZ (E:\fanbianyi\wxappUnpacker-master\wuRestoreZ.js:19:29)
    at getZ (E:\fanbianyi\wxappUnpacker-master\wuRestoreZ.js:244:2)
    at wu.get.code (E:\fanbianyi\wxappUnpacker-master\wuWxml.js:354:3)
    at ioLimit.runWithCb (E:\fanbianyi\wxappUnpacker-master\wuLib.js:80:8)
    at agent (E:\fanbianyi\wxappUnpacker-master\wuLib.js:54:14)
```

程序结果错误信息(如果反馈不是抛出异常的错误, 必填, 请尽可能详细描述):

其他附加内容:

**Comment by qwerty472123** [comment]
没有提供包 没法具体分析
不过按这个来看很可能是版本过低或包含插件
前者不予支持 后者请自行删除requirePlugin definePlugin和plugin的wxml信息等内容后重试
