### ISSUE TITLE
使用wuJs.js解压app-service.js文件出现console is not defined错误

### ISSUE THREAD

**Issue by cn-qlg** [qwerty472123/wxappUnpacker#16]
程序执行命令(可选)：D:\小程序\wxappUnpacker-master>node wuJs.js D:\小程序\jd_weixuan\app-service.js

程序执行错误信息（如果反馈是抛出异常的错误，必填）:

D:\小程序\wxappUnpacker-master\node_modules\vm2\lib\main.js:218
                        throw this._internal.Decontextify.value(e);
                        ^
ReferenceError: console is not defined
    at $gwx (vm.js:14:6)
    at vm.js:3520:70
    at ContextifyScript.Script.runInContext (vm.js:53:29)
    at VM.run (D:\小程序\wxappUnpacker-master\node_modules\vm2\lib\main.js:212:72)
    at wu.get.code (D:\小程序\wxappUnpacker-master\wuJs.js:18:6)
    at fs.readFile (D:\小程序\wxappUnpacker-master\wuLib.js:48:8)
    at tryToString (fs.js:512:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:500:12)

程序结果错误信息（如果反馈不是抛出异常的错误，必填，请尽可能详细描述）:

程序包地址：
使用的是https://gist.github.com/feix/32ab8f0dfe99aa8efa84f81ed68a0f3e这个工具解压的，解压之后问下如下：
链接: https://pan.baidu.com/s/1SSjTaS49mCxgwJhmLNiN5g 密码: zkpx

其他附加内容：

**Comment by cn-qlg** [comment]
另外在使用node wuWxapkg.js D:\小程序\_2137208754_10.wxapkg这个命令解压小程序文件的时候，报同样的错。

**Comment by qwerty472123** [comment]
可以给出 原始 wxapkg 包吗？

**Comment by qwerty472123** [comment]
随便搞了搞，这个包太奇葩了，有些内容在两个文件里重复出现，强行ignore掉一些

**Comment by cn-qlg** [comment]
[_2137208754_10.txt](https://github.com/qwerty472123/wxappUnpacker/files/1851135/_2137208754_10.txt)
改一下后缀
