### ISSUE TITLE
解压小程序出错了, 麻烦帮忙看看,谢谢

### ISSUE THREAD

**Issue by zhq426** [qwerty472123/wxappUnpacker#163]
(如果你是要反馈 bug, 请按以下格式书写 Issue; 如果你遇到的是 Node.js 使用问题, 请尽可能依赖搜索引擎解决问题; 任何对某类小程序包的适配问题都应提供 wxapkg 程序包，否则直接 Close 处理; 提交前请确认 wxapkg 程序包版本不小于 v0.6vv_20180111_fbi (直接用文本编辑器打开 wxapkg包搜索 v0.6vv 或 v0.5vv 即可查到，注意版本大小主要比较的是日期), 旧版本不提供支持, 相关 Issue 直接 Close 处理。)

v0.5vv_20180905_syb_scopedata

程序执行命令(可选):

程序执行错误信息(如果反馈是抛出异常的错误，必填):

```
D:\svn\sourcetree\wxappUnpacker\node_modules\vm2\lib\main.js:210
                        throw this._internal.Decontextify.value(e);
                        ^
vm.js:450
return function(env,dd,global){$gwxc=0;var root={"tag":"wx-page"};root.children=[]
^^^^^^

SyntaxError: Illegal return statement
    at new Script (vm.js:73:7)
    at VMScript.compile (D:\svn\sourcetree\wxappUnpacker\node_modules\vm2\lib\main.js:78:20)
    at VM.run (D:\svn\sourcetree\wxappUnpacker\node_modules\vm2\lib\main.js:204:52)
    at z (D:\svn\sourcetree\wxappUnpacker\wuWxml.js:366:7)
    at z (D:\svn\sourcetree\wxappUnpacker\wuRestoreZ.js:244:17)
    at catchZGroup (D:\svn\sourcetree\wxappUnpacker\wuRestoreZ.js:15:2)
    at catchZ (D:\svn\sourcetree\wxappUnpacker\wuRestoreZ.js:19:29)
    at getZ (D:\svn\sourcetree\wxappUnpacker\wuRestoreZ.js:244:2)
    at wu.get.code (D:\svn\sourcetree\wxappUnpacker\wuWxml.js:354:3)
    at ioLimit.runWithCb (D:\svn\sourcetree\wxappUnpacker\wuLib.js:80:8)

```

程序结果错误信息(如果反馈不是抛出异常的错误, 必填, 请尽可能详细描述):

程序包(你所要解压的程序包地址, 可为网盘链接, 也可直接上传[上传前请先打包]. 必填):
链接：https://pan.baidu.com/s/1w9H5ccnb7C6gtRD2Odd0ag 
提取码：n68b
其他附加内容:

**Comment by zhq426** [comment]
> 该包中有插件 暂不支持可将page-frame.html中第一个/_v0.5vv_20180905_syb_scopedata_/到第二个/_v0.5vv_20180905_syb_scopedata_/见的代码删去后用wuwxml.js解包非插件部分wxml

删除后还是不行,报下面的错误了... 你可以帮忙解压后, 发下给我吗.

`D:\svn\sourcetree\wxappUnpacker\node_modules\vm2\lib\main.js:210
                        throw this._internal.Decontextify.value(e);
                        ^
vm.js:450
return function(env,dd,global){$gwxc=0;var root={"tag":"wx-page"};root.children=[]
^^^^^^

SyntaxError: Illegal return statement
    at new Script (vm.js:73:7)
    at VMScript.compile (D:\svn\sourcetree\wxappUnpacker\node_modules\vm2\lib\main.js:78:20)
    at VM.run (D:\svn\sourcetree\wxappUnpacker\node_modules\vm2\lib\main.js:204:52)
    at z (D:\svn\sourcetree\wxappUnpacker\wuWxml.js:366:7)
    at z (D:\svn\sourcetree\wxappUnpacker\wuRestoreZ.js:244:17)
    at catchZGroup (D:\svn\sourcetree\wxappUnpacker\wuRestoreZ.js:15:2)
    at catchZ (D:\svn\sourcetree\wxappUnpacker\wuRestoreZ.js:19:29)
    at getZ (D:\svn\sourcetree\wxappUnpacker\wuRestoreZ.js:244:2)
    at wu.get.code (D:\svn\sourcetree\wxappUnpacker\wuWxml.js:354:3)
    at ioLimit.runWithCb (D:\svn\sourcetree\wxappUnpacker\wuLib.js:80:8)`

**Comment by qwerty472123** [comment]
可能是前述内容中有一些因为被markdown转义造成你操作上的问题 目前已经修改 请重试
解包后的代码恕不提供 本人无权发表相关内容
