### ISSUE TITLE
解析文件报错

### ISSUE THREAD

**Issue by yuanwenyu** [qwerty472123/wxappUnpacker#17]
(如果你是要反馈 bug，请按以下格式书写 Issue )

程序执行命令(可选)：
node wuWxapkg.js flie
程序执行错误信息（如果反馈是抛出异常的错误，必填）:

module.js:540
    throw err;
    ^

Error: Cannot find module 'uglify-es'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/ywy/Downloads/wxappUnpacker-master/wuJs.js:3:16)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)

程序结果错误信息（如果反馈不是抛出异常的错误，必填，请尽可能详细描述）:
已经安装了uglify-es 还是报错说没有找到，其他的模块vm2 这些也是找不到
程序包地址（你所解压的程序包地址，可为网盘，也可直接上传，如果不愿意公开，请附上具体出错的文件）：

其他附加内容：

**Comment by qwerty472123** [comment]
你可以翻翻 #8 ，也可以网上查查node.js的用法。这样一个issue的信息量不足以解决问题的。
