### ISSUE TITLE
报错，我感觉我用这怎么就重来就没有成功过呀。都快一年了。

### ISSUE THREAD

**Issue by yorick520** [qwerty472123/wxappUnpacker#177]
D:\Program Files\nodejs>node E:\fanbianyi\wxappUnpacker-master\wuWxml.js E:\fanb
ianyi\demo\aaa\1670088044_75\page-frame.html

D:\Program Files\nodejs\node_modules\node_global\node_modules\vm2\lib\main.js:21
0
                        throw this._internal.Decontextify.value(e);
                        ^
SyntaxError: Illegal return statement
    at VMScript.compile (D:\Program Files\nodejs\node_modules\node_global\node_m
odules\vm2\lib\main.js:78:20)
    at VM.run (D:\Program Files\nodejs\node_modules\node_global\node_modules\vm2
\lib\main.js:204:52)
    at z (E:\fanbianyi\wxappUnpacker-master\wuWxml.js:366:7)
    at z (E:\fanbianyi\wxappUnpacker-master\wuRestoreZ.js:244:17)
    at catchZGroup (E:\fanbianyi\wxappUnpacker-master\wuRestoreZ.js:15:2)
    at catchZ (E:\fanbianyi\wxappUnpacker-master\wuRestoreZ.js:19:29)
    at getZ (E:\fanbianyi\wxappUnpacker-master\wuRestoreZ.js:244:2)
    at wu.get.code (E:\fanbianyi\wxappUnpacker-master\wuWxml.js:354:3)
    at ioLimit.runWithCb (E:\fanbianyi\wxappUnpacker-master\wuLib.js:80:8)
    at agent (E:\fanbianyi\wxappUnpacker-master\wuLib.js:54:14)

D:\Program Files\nodejs>

**Comment by yorick520** [comment]
后面我又换了个包，结果解析出
page-frame.js内容：
var __pageFrameJsStartTime__ = Date.now();
没有page-frame.html

**Comment by ayackcn** [comment]
教你一招。
在E:\fanbianyi\wxappUnpacker-master 目录，右键 打开命令行。然后 wuWxml.js 把要解析的文件拉cmd里面。。回车
省的那么麻烦。。

**Comment by qwerty472123** [comment]
1670088044_75的版本太低 一开始就不支持
还有一个_77086400_56有插件和子包 暂不支持
这个项目我作为娱乐而写的，所以只会在有闲下来的时候才有可能完善
当然这些“不成功”的包你调整一下包内容也是可以解的
一直拖着的原因则是原先分解包后类型解码的方法在插件、子包下要增加的逻辑比较麻烦 我也不想重构

**Comment by wangheng669** [comment]
我想问下你们解决了么...
