### ISSUE TITLE
运行异常，尝试通过Issues查找原因无果

### ISSUE THREAD

**Issue by sexbank** [qwerty472123/wxappUnpacker#181]
程序执行命令(可选):
C:\wxappUnpacker\wxappUnpacker-master>node .wuWxapkg.js C:\wxappUnpacker\_112399441_195.wxapkg
程序执行错误信息(如果反馈是抛出异常的错误，必填):
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module 'C:\wxappUnpacker\wxappUnpacker-master\.wuWxapkg.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)

程序包：
https://pan.baidu.com/s/1FMMOT-3AMEeKUWrsrIDnMQ

谢谢老师百忙之中解决我的问题

**Comment by qwerty472123** [comment]
你命令里`node .wuWxapkg`中的`.`是哪里来的
请按README.md操作
