### ISSUE TITLE
wxml无法反编译 ：Unknown init callee

### ISSUE THREAD

**Issue by gaozp** [qwerty472123/wxappUnpacker#186]
程序执行命令(可选):
node wuWxml.js pkg/_1409690042_19/page-frame.html 

程序执行错误信息(如果反馈是抛出异常的错误，必填):

node wuWxml.js pkg/_1409690042_19/page-frame.html 
Decompile ./components/customImage/customImage.wxml...
error on ./components/customImage/customImage.wxml
err:  Error: Unknown init callee gz$gwx_1
    at analyze (/home/ihsan/tools/wxappUnpackerGameBox-master/wuWxml.js:136:22)
    at doWxml (/home/ihsan/tools/wxappUnpackerGameBox-master/wuWxml.js:248:2)
    at tryWxml (/home/ihsan/tools/wxappUnpackerGameBox-master/wuWxml.js:267:3)
    at z (/home/ihsan/tools/wxappUnpackerGameBox-master/wuWxml.js:311:23)
    at z (/home/ihsan/tools/wxappUnpackerGameBox-master/wuRestoreZ.js:216:17)
    at catchZ (/home/ihsan/tools/wxappUnpackerGameBox-master/wuRestoreZ.js:12:2)
    at getZ (/home/ihsan/tools/wxappUnpackerGameBox-master/wuRestoreZ.js:216:2)
    at wu.get.code (/home/ihsan/tools/wxappUnpackerGameBox-master/wuWxml.js:282:3)
    at ioLimit.runWithCb (/home/ihsan/tools/wxappUnpackerGameBox-master/wuLib.js:80:8)
    at agent (/home/ihsan/tools/wxappUnpackerGameBox-master/wuLib.js:54:14)

程序包(你所要解压的程序包地址, 可为网盘链接, 也可直接上传[上传前请先打包]. 必填):
_1409690042_19.wxapkg
https://drive.google.com/file/d/1WQWbwfc00Nea3pGASm9jwb1bwFR1yKaJ/view?usp=sharing

其他：
版本： v0.5vv_20180626

**Comment by onep2p** [comment]
请问你解决了吗？   我也遇到这个问题了

**Comment by gaozp** [comment]
@onep2p 没法解决，后来放弃反编译那个包了。

**Comment by onep2p** [comment]
噢  好的  感谢

**Comment by 7423385** [comment]
解包出现各种问题可以联系我的QQ7423385，可以帮忙解决
