### ISSUE TITLE
错误提示：SyntaxError: Illegal return statement

### ISSUE THREAD

**Issue by wuearl** [qwerty472123/wxappUnpacker#19]
(如果你是要反馈 bug, 请按以下格式书写 Issue; 如果你遇到的是Node.JS使用问题, 请尽可能依赖搜索引擎解决问题)

程序执行命令(可选):node wuWxapkg.js [-d] <files...>

程序执行错误信息(如果反馈是抛出异常的错误，必填):

```
{ name: '/think/template/template.html', off: 707015, size: 198 }
Saving files...
Unpack done.
Split app-service.js and make up configs & wxss & wxml & wxs...

E:\sou\wxappUnpacker\node_modules\vm2\lib\main.js:218
                        throw this._internal.Decontextify.value(e);
                        ^
SyntaxError: Illegal return statement
    at VMScript.compile (E:\sou\wxappUnpacker\node_modules\vm2\lib\main.js:78:20)
    at VM.run (E:\sou\wxappUnpacker\node_modules\vm2\lib\main.js:212:52)
    at wu.get.code (E:\sou\wxappUnpacker\wuWxml.js:291:7)
    at fs.readFile (E:\sou\wxappUnpacker\wuLib.js:48:8)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
```

程序结果错误信息(如果反馈不是抛出异常的错误, 必填, 请尽可能详细描述):

程序包(你所要解压的程序包地址, 可为网盘链接, 也可直接上传[上传前请先打包]. 如果不愿意公开, 请附上具体出错的文件):链接：https://pan.baidu.com/s/10ANkSWkibIaI6jI3ZH1w1Q 密码：e32z

其他附加内容:

**Comment by qwerty472123** [comment]
该包‘编译’自`v0.6vv_20170109_fbi`版本的微信‘编译器’而非本程序支持的`v0.6vv_20180111_fbi`。除非重新适配，要做的改动还是蛮大的，话说这个程序也太老了吧。

**Comment by wuearl** [comment]
噢噢  谢谢
