### ISSUE TITLE
编译小程序错误

### ISSUE THREAD

**Issue by 1yiGer** [qwerty472123/wxappUnpacker#190]
Guess wxss(first turn)...

C:\Users\ZY\Desktop\wxappUnpacker-0.3\node_modules\vm2\lib\main.js:214
                        throw this._internal.Decontextify.value(e);
                        ^
ReferenceError: $gwx is not defined
    at vm.js:3:3
    at Script.runInContext (vm.js:107:20)
    at VM.run (C:\Users\ZY\Desktop\wxappUnpacker-0.3\node_modules\vm2\lib\main.js:208:72)
    at runVM (C:\Users\ZY\Desktop\wxappUnpacker-0.3\wuWxss.js:69:6)
    at runOnce (C:\Users\ZY\Desktop\wxappUnpacker-0.3\wuWxss.js:86:27)
    at Array.preRun (C:\Users\ZY\Desktop\wxappUnpacker-0.3\wuWxss.js:166:5)
    at CntEvent.decount (C:\Users\ZY\Desktop\wxappUnpacker-0.3\wuLib.js:17:43)
    at ioLimit.runWithCb (C:\Users\ZY\Desktop\wxappUnpacker-0.3\wuLib.js:81:11)
    at agent (C:\Users\ZY\Desktop\wxappUnpacker-0.3\wuLib.js:54:14)
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)

**Comment by Shawn2046** [comment]
我也遇到了这个问题，请问你找到解决办法了吗？

**Comment by gaohongwei0501** [comment]
顶上去，求大神帮忙

**Comment by davidlin88** [comment]
一样 node node wuWxapkg.js后再wuWxss.js时发生的

**Comment by aaaTang** [comment]
> Guess wxss(first turn)...
> 
> C:\Users\ZY\Desktop\wxappUnpacker-0.3\node_modules\vm2\lib\main.js:214
> throw this._internal.Decontextify.value(e);
> ^
> ReferenceError: $gwx is not defined
> at vm.js:3:3
> at Script.runInContext (vm.js:107:20)
> at VM.run (C:\Users\ZY\Desktop\wxappUnpacker-0.3\node_modules\vm2\lib\main.js:208:72)
> at runVM (C:\Users\ZY\Desktop\wxappUnpacker-0.3\wuWxss.js:69:6)
> at runOnce (C:\Users\ZY\Desktop\wxappUnpacker-0.3\wuWxss.js:86:27)
> at Array.preRun (C:\Users\ZY\Desktop\wxappUnpacker-0.3\wuWxss.js:166:5)
> at CntEvent.decount (C:\Users\ZY\Desktop\wxappUnpacker-0.3\wuLib.js:17:43)
> at ioLimit.runWithCb (C:\Users\ZY\Desktop\wxappUnpacker-0.3\wuLib.js:81:11)
> at agent (C:\Users\ZY\Desktop\wxappUnpacker-0.3\wuLib.js:54:14)
> at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)

你好，麻烦问一下解决了这个问题吗
