### ISSUE TITLE
wxss新的解析不了

### ISSUE THREAD

**Issue by gs053507** [qwerty472123/wxappUnpacker#197]
https://pan.baidu.com/s/1F2LRwYt6ueZHX66W6B2C_w

Decompile ./utils/wxParse/wxParse.wxml...
Decompile success!
Guess wxss(first turn)...

H:\8\node_modules\vm2\lib\main.js:210
                        throw this._internal.Decontextify.value(e
                        ^
ReferenceError: __mainPageFrameReady__ is not defined
    at vm.js:49:5
    at ContextifyScript.Script.runInContext (vm.js:59:29)
    at VM.run (H:\8\node_modules\vm2\lib\main.js:204:72)
    at runVM (H:\8\wuWxss.js:69:6)
    at runOnce (H:\8\wuWxss.js:86:27)
    at Array.preRun (H:\8\wuWxss.js:166:5)
    at CntEvent.decount (H:\8\wuLib.js:17:43)
    at ioLimit.runWithCb (H:\8\wuLib.js:81:11)
    at agent (H:\8\wuLib.js:54:14)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)

**Comment by gs053507** [comment]
直接删除了 编译了一点出来

**Comment by Rayure** [comment]
解决了吗这个问题
