### ISSUE TITLE
不知这个bug怎么解决啊

### ISSUE THREAD

**Issue by zxp01** [qwerty472123/wxappUnpacker#202]
程序执行错误信息(如果反馈是抛出异常的错误，必填):

F:\wxapp\wxappUnpacker20180821\wxappUnpacker\node_modules\vm2\lib\main.js:210
                        throw this._internal.Decontextify.value(e);
                        ^
ReferenceError: __mainPageFrameReady__ is not defined
    at vm.js:85:5
    at ContextifyScript.Script.runInContext (vm.js:59:29)
    at VM.run (F:\wxapp\wxappUnpacker20180821\wxappUnpacker\node_modules\vm2\lib\main.js:204:72)
    at runVM (F:\wxapp\wxappUnpacker20180821\wxappUnpacker\wuWxss.js:69:6)
    at runOnce (F:\wxapp\wxappUnpacker20180821\wxappUnpacker\wuWxss.js:86:27)
    at Array.preRun (F:\wxapp\wxappUnpacker20180821\wxappUnpacker\wuWxss.js:166:5)
    at CntEvent.decount (F:\wxapp\wxappUnpacker20180821\wxappUnpacker\wuLib.js:17:43)
    at ioLimit.runWithCb (F:\wxapp\wxappUnpacker20180821\wxappUnpacker\wuLib.js:81:11)
    at agent (F:\wxapp\wxappUnpacker20180821\wxappUnpacker\wuLib.js:54:14)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)

程序结果错误信息(如果反馈不是抛出异常的错误, 必填, 请尽可能详细描述):

程序包(你所要解压的程序包地址, 可为网盘链接, 也可直接上传[
[234fed56cce796_109.zip](https://github.com/qwerty472123/wxappUnpacker/files/2794715/234fed56cce796_109.zip)
上传前请先打包]. 必填):

其他附加内容:

**Comment by xjd1123** [comment]
这个不是Bug,这个是微信更新了规则导致的，反编译工具需要针对新规则适配。作者比较忙，所以应该没有更新吧，或者怕更新出来对微信生态不好。
http://thyrsi.com/t6/662/1548410108x2890174321.jpg
你这个帮你解了，jpg改成zip解压即可。

**Comment by gulei01** [comment]
https://share.weiyun.com/5NqJzAv   能否有时间帮忙看看这个十分感谢！@xjd1123

**Comment by xjd1123** [comment]
http://thyrsi.com/t6/662/1548474917x2890174094.jpg 
@gulei01 帮你解了，jpg改成zip即可

**Comment by gulei01** [comment]
@xjd1123 十分感谢高手！能不能加个Q

**Comment by wwjjazz** [comment]
同求解决方法@gulei01

**Comment by 7423385** [comment]
> 同求解决方法@gulei01

解包出现各种问题可以联系我的QQ7423385，可以帮忙解决

**Comment by 7423385** [comment]
> 遇到同样的问题，需要怎么解决呢？？？？？@xjd1123 能否说明清楚一些，怎么做的》》》》

解包出现各种问题可以联系我的QQ7423385，可以帮忙解决

**Comment by 7423385** [comment]
> @xjd1123 十分感谢高手！能不能加个Q

解包出现各种问题可以联系我的QQ7423385，可以帮忙解决

**Comment by 7423385** [comment]
> 遇到同样的问题，需要怎么解决呢？？？？？@xjd1123 能否说明清楚一些，怎么做的》》》》

解包出现各种问题可以联系我的QQ7423385，可以帮忙解决

**Comment by 7423385** [comment]
> https://share.weiyun.com/5NqJzAv 能否有时间帮忙看看这个十分感谢！@xjd1123

解包出现各种问题可以联系我的QQ7423385，可以帮忙解决

**Comment by 7423385** [comment]
QQ7423385 解包

**Comment by showching** [comment]
参考 #200  ，看我的回复
感谢作者！
