### ISSUE TITLE
解压缩第三个包时报错

### ISSUE THREAD

**Issue by csnero** [qwerty472123/wxappUnpacker#203]
程序执行命令(可选):
step1：node wuWxapkg.js -o ../resource/_1123949441_171.wxapkg
执行成功；
step2： node wuWxapkg.js -o ../resource/_1739533637_61.wxapkg
执行成功；
step3：node wuWxapkg.js -o ../resource/484675448_61.wxapkg
执行报错。
程序执行错误信息(如果反馈是抛出异常的错误，必填):

```
 path\to\wxappUnpacker-master\wuLib.js:79
		if(err)throw Error("Read file error: "+err);
		       ^

Error: Read file error: Error: ENOENT: no such file or directory, open ' path\to\484675448_61.wxapkg'
    at ReadFileContext.ioLimit.runWithCb  path\to\wxappUnpacker-master\wuLib.js:79:16)
    at ReadFileContext.agent [as callback] ( path\to\wxappUnpacker-master\wuLib.js:54:14)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:238:13)

```

程序结果错误信息(如果反馈不是抛出异常的错误, 必填, 请尽可能详细描述):

程序包(你所要解压的程序包地址, 可为网盘链接, 也可直接上传[上传前请先打包]. 必填):
[https://pan.baidu.com/s/1UPqJlpa29tYW4blNxu9GUA](url)

**Comment by 7423385** [comment]
> 程序执行命令(可选):
> step1：node wuWxapkg.js -o ../resource/_1123949441_171.wxapkg
> 执行成功；
> step2： node wuWxapkg.js -o ../resource/_1739533637_61.wxapkg
> 执行成功；
> step3：node wuWxapkg.js -o ../resource/484675448_61.wxapkg
> 执行报错。
> 程序执行错误信息(如果反馈是抛出异常的错误，必填):
> 
> ```
>  path\to\wxappUnpacker-master\wuLib.js:79
> 		if(err)throw Error("Read file error: "+err);
> 		       ^
> 
> Error: Read file error: Error: ENOENT: no such file or directory, open ' path\to\484675448_61.wxapkg'
>     at ReadFileContext.ioLimit.runWithCb  path\to\wxappUnpacker-master\wuLib.js:79:16)
>     at ReadFileContext.agent [as callback] ( path\to\wxappUnpacker-master\wuLib.js:54:14)
>     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:238:13)
> ```
> 程序结果错误信息(如果反馈不是抛出异常的错误, 必填, 请尽可能详细描述):
> 
> 程序包(你所要解压的程序包地址, 可为网盘链接, 也可直接上传[上传前请先打包]. 必填):
> [https://pan.baidu.com/s/1UPqJlpa29tYW4blNxu9GUA](url)

解包出现各种问题可以联系我的QQ7423385，可以帮忙解决
