### ISSUE TITLE
解包报错$gwx is not defined，请帮忙解包，谢谢！

### ISSUE THREAD

**Issue by lovexingqiba** [qwerty472123/wxappUnpacker#204]
想研究一下某个小程序的sign加密算法，按照教程解包报错了。

```
Decompile ./zanui/actionsheet/index.wxml...
Decompile success!
Decompile ./zanui/dialog/index.wxml...
Decompile success!
Guess wxss(first turn)...

C:\Users\Administrator\Desktop\wxappUnpacker-master\node_modules\vm2\lib\main.js:214
                        throw this._internal.Decontextify.value(e);
                        ^
ReferenceError: $gwx is not defined
    at vm.js:3:3
    at Script.runInContext (vm.js:107:20)
```
wxapkg已经上传到我的个人网盘，下载链接如下：
[http://p.wjfei.com:8000/f/dbd4af0f5cfb41dea7f5/?dl=1](url)

**Comment by lishouqiang** [comment]
2019最新的小程序反编译工具和方法 https://www.jianshu.com/p/53e97423383e

**Comment by 7423385** [comment]
> 想研究一下某个小程序的sign加密算法，按照教程解包报错了。
> 
> ```
> Decompile ./zanui/actionsheet/index.wxml...
> Decompile success!
> Decompile ./zanui/dialog/index.wxml...
> Decompile success!
> Guess wxss(first turn)...
> 
> C:\Users\Administrator\Desktop\wxappUnpacker-master\node_modules\vm2\lib\main.js:214
>                         throw this._internal.Decontextify.value(e);
>                         ^
> ReferenceError: $gwx is not defined
>     at vm.js:3:3
>     at Script.runInContext (vm.js:107:20)
> ```
> wxapkg已经上传到我的个人网盘，下载链接如下：
> [http://p.wjfei.com:8000/f/dbd4af0f5cfb41dea7f5/?dl=1](url)

解包出现各种问题可以联系我的QQ7423385，可以帮忙解决

**Comment by chriiess** [comment]
方法一：
修改wuWxcss.js文件
找到这个方法runVM
替换
`function runVM(name,code){
	let wxAppCode={},handle={cssFile:name};
	let gg= new GwxCfg();
	let tsandbox={
		$gwx:GwxCfg.prototype["$gwx"],
		__mainPageFrameReady__:GwxCfg.prototype["$gwx"],
		__wxAppCode__:wxAppCode,
		setCssToHead:cssRebuild.bind(handle)
	}
	let vm=new VM({sandbox:tsandbox});
	vm.run(code);
}`
方法二：
使用这个
https://github.com/larack8/wxappUnpacker
