### ISSUE TITLE
 esprima.parseScript is not a function

### ISSUE THREAD

**Issue by museL** [qwerty472123/wxappUnpacker#209]
error on ./pages/zeroGoodsIntro/zeroGoodsIntro.wxml(Main)
err:  TypeError: esprima.parseScript is not a function
    at doWxml (D:\wxappUnpacker-master\wuWxml.js:311:18)
    at tryWxml (D:\wxappUnpacker-master\wuWxml.js:339:3)
    at z (D:\wxappUnpacker-master\wuWxml.js:385:23)
    at z (D:\wxappUnpacker-master\wuRestoreZ.js:244:17)
    at catchZGroup (D:\wxappUnpacker-master\wuRestoreZ.js:15:2)
    at catchZ (D:\wxappUnpacker-master\wuRestoreZ.js:19:29)
    at getZ (D:\wxappUnpacker-master\wuRestoreZ.js:244:2)
    at wu.get.code (D:\wxappUnpacker-master\wuWxml.js:355:3)
    at ioLimit.runWithCb (D:\wxappUnpacker-master\wuLib.js:80:8)
    at agent (D:\wxappUnpacker-master\wuLib.js:54:14)
解不开 wxml 求方法

**Comment by museL** [comment]
链接: https://pan.baidu.com/s/1eueHZJimch12rPytQYeucw 提取码: he7j 谁能帮忙解一下

**Comment by xjd1123** [comment]
@museL 下载后把.jpg改成zip解压即可！
http://thyrsi.com/t6/670/1549976714x2890174243.jpg

**Comment by 7423385** [comment]
> 链接: https://pan.baidu.com/s/1eueHZJimch12rPytQYeucw 提取码: he7j 谁能帮忙解一下
> @xjd1123大佬帮帮忙

解包出现各种问题可以联系我的QQ7423385，可以帮忙解决

**Comment by xjd1123** [comment]
一切以收费为前提的都可能是骗子，谨防骗子QQ7423385。要解什么发出来，我有空了就免费帮解的！

**Comment by 7423385** [comment]
> 一切以收费为前提的都可能是骗子，谨防骗子QQ7423385。要解什么发出来，我有空了就免费帮解的！

神经病

**Comment by 7423385** [comment]
> 一切以收费为前提的都可能是骗子，谨防骗子QQ7423385。要解什么发出来，我有空了就免费帮解的！

有病吧 我骗啥了? 你愿意有空的时候免费解是你的事，我随时都有空解 关你屌事，有本事你把方法都公布出来呗，藏着掖着干嘛？

**Comment by xjd1123** [comment]
这本来就是免费分享的东西，你来这里打广告收费还有理了，你要收费去其他地方打广告呗，你向qwerty472123交了版权费吗，别人免费的东西你收费有脸了。

**Comment by 7423385** [comment]
> 这本来就是免费分享的东西，你来这里打广告收费还有理了，你要收费去其他地方打广告呗，你向qwerty472123交了版权费吗，别人免费的东西你收费有脸了。

别人愿意公布是别人的事，我强迫别人了还是怎么的？你这么牛逼直接公开方法呗  你藏着干嘛啊?

**Comment by 7423385** [comment]
> 这本来就是免费分享的东西，你来这里打广告收费还有理了，你要收费去其他地方打广告呗，你向qwerty472123交了版权费吗，别人免费的东西你收费有脸了。

看别人赚钱眼红了?可笑
