### ISSUE TITLE
还原wxapkg文件，控制台报错

### ISSUE THREAD

**Issue by youbooks** [qwerty472123/wxappUnpacker#21]
(如果你是要反馈 bug, 请按以下格式书写 Issue; 如果你遇到的是Node.JS使用问题, 请尽可能依赖搜索引擎解决问题)

程序执行命令(可选):
 node wuWxapkg.js -d /usr/local/testweixin/newweixin/_1340083664_9.wxapkg 
程序执行错误信息(如果反馈是抛出异常的错误，必填):

```
error on ./pages/view_h/index.wxml
err:  Error: Empty str in prop
    at wxmlify (/usr/local/testweixin/wxappUnpacker-master/wuWxml.js:176:47)
    at elemToString (/usr/local/testweixin/wxappUnpacker-master/wuWxml.js:230:57)
    at doWxml (/usr/local/testweixin/wxappUnpacker-master/wuWxml.js:247:33)
    at tryWxml (/usr/local/testweixin/wxappUnpacker-master/wuWxml.js:264:3)
    at wu.get.code (/usr/local/testweixin/wxappUnpacker-master/wuWxml.js:308:23)
    at fs.readFile (/usr/local/testweixin/wxappUnpacker-master/wuLib.js:48:8)
    at tryToString (fs.js:449:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:436:12)
Decompile ./pages/view_v/index.wxml...
error on ./pages/view_v/index.wxml
err:  Error: Empty str in prop
    at wxmlify (/usr/local/testweixin/wxappUnpacker-master/wuWxml.js:176:47)
    at elemToString (/usr/local/testweixin/wxappUnpacker-master/wuWxml.js:230:57)
    at doWxml (/usr/local/testweixin/wxappUnpacker-master/wuWxml.js:247:33)
    at tryWxml (/usr/local/testweixin/wxappUnpacker-master/wuWxml.js:264:3)
    at wu.get.code (/usr/local/testweixin/wxappUnpacker-master/wuWxml.js:308:23)
    at fs.readFile (/usr/local/testweixin/wxappUnpacker-master/wuLib.js:48:8)
    at tryToString (fs.js:449:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:436:12)

/usr/local/testweixin/wxappUnpacker-master/node_modules/vm2/lib/main.js:218
			throw this._internal.Decontextify.value(e);
			^
ReferenceError: _C is not defined
    at vm.js:2:1
    at ContextifyScript.Script.runInContext (vm.js:32:29)
    at VM.run (/usr/local/testweixin/wxappUnpacker-master/node_modules/vm2/lib/main.js:212:72)
    at wu.get.code (/usr/local/testweixin/wxappUnpacker-master/wuWxss.js:127:16)
    at fs.readFile (/usr/local/testweixin/wxappUnpacker-master/wuLib.js:48:8)
    at tryToString (fs.js:449:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:436:12)
[root@VM_17_68_centos wxappUnpacker-master]# 


```

程序结果错误信息(如果反馈不是抛出异常的错误, 必填, 请尽可能详细描述):

感谢你写了这么好的工具，我在使用过程中发现控制台有报错，日志如上所述，还原的结果是没有出现wxml和wxss文件，能麻烦作者帮我看下吗？ 我的压缩包在附件中
[_1340083664_9.zip](https://github.com/qwerty472123/wxappUnpacker/files/1854266/_1340083664_9.zip)

程序包(你所要解压的程序包地址, 可为网盘链接, 也可直接上传[上传前请先打包]. 如果不愿意公开, 请附上具体出错的文件):

其他附加内容:

**Comment by qwerty472123** [comment]
该包‘编译’自`v0.6vv_20171120_cua_xc`版本的微信‘编译器’而非本程序支持的`v0.6vv_20180111_fbi`。除非重新适配，要做的改动还是蛮大的。

**Comment by youbooks** [comment]
感谢你的回复，关于适配问题，能麻烦大神 抽点时间 适配下嘛，拜托了

**Comment by qwerty472123** [comment]
大概要周末再说了...

**Comment by youbooks** [comment]
OK, 幸苦了

**Comment by zjjzff1** [comment]
我也碰到这个问题了，我看了下小程序是17年10月份提交的，还望做下适配

**Comment by youbooks** [comment]
还是这个wxapkg文件 解析问题， 通过阅读 作者提供的这个文档 
 https://github.com/qwerty472123/wxappUnpacker/blob/master/DETAILS.md ， 我本人试着尝试解决这个issue , 发现 一如既往的
报异常：
Saving files...
Unpack done.
Split app-service.js and make up configs & wxss & wxml & wxs...
Decompile ./pages/a/create/index.wxml...
error on ./pages/a/create/index.wxml
err:  Error: Empty str in prop
    at Error (native)
    at wxmlify (/usr/local/weixinapp/wuWxml.js:176:47)
    at elemToString (/usr/local/weixinapp/wuWxml.js:230:57)
    at doWxml (/usr/local/weixinapp/wuWxml.js:247:33)
    at tryWxml (/usr/local/weixinapp/wuWxml.js:264:3)
    at wu.get.code (/usr/local/weixinapp/wuWxml.js:308:23)
    at fs.readFile (/usr/local/weixinapp/wuLib.js:48:8)
    at tryToString (fs.js:457:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:444:12)
Decompile ./pages/a/index.wxml...
error on ./pages/a/index.wxml
err:  Error: Empty str in prop
    at Error (native)
    at wxmlify (/usr/local/weixinapp/wuWxml.js:176:47)
    at elemToString (/usr/local/weixinapp/wuWxml.js:230:57)
    at elemRecursion (/usr/local/weixinapp/wuWxml.js:187:10)
    at elemToString (/usr/local/weixinapp/wuWxml.js:221:12)
    at elemRecursion (/usr/local/weixinapp/wuWxml.js:187:10)
    at elemToString (/usr/local/weixinapp/wuWxml.js:221:12)
    at doWxml (/usr/local/weixinapp/wuWxml.js:247:33)
    at tryWxml (/usr/local/weixinapp/wuWxml.js:264:3)
    at wu.get.code (/usr/local/weixinapp/wuWxml.js:308:23)
Decompile ./pages/choose/index.wxml...
error on ./pages/choose/index.wxml
err:  Error: Empty str in prop
    at Error (native)
    at wxmlify (/usr/local/weixinapp/wuWxml.js:176:47)
    at elemToString (/usr/local/weixinapp/wuWxml.js:230:57)
    at doWxml (/usr/local/weixinapp/wuWxml.js:247:33)
    at tryWxml (/usr/local/weixinapp/wuWxml.js:264:3)
    at wu.get.code (/usr/local/weixinapp/wuWxml.js:308:23)
    at fs.readFile (/usr/local/weixinapp/wuLib.js:48:8)
    at tryToString (fs.js:457:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:444:12)
Decompile ./pages/edit_info/index.wxml...
error on ./pages/edit_info/index.wxml
err:  Error: Empty str in prop
    at Error (native)
    at wxmlify (/usr/local/weixinapp/wuWxml.js:176:47)
    at elemToString (/usr/local/weixinapp/wuWxml.js:230:57)
    at doWxml (/usr/local/weixinapp/wuWxml.js:247:33)
    at tryWxml (/usr/local/weixinapp/wuWxml.js:264:3)
    at wu.get.code (/usr/local/weixinapp/wuWxml.js:308:23)
    at fs.readFile (/usr/local/weixinapp/wuLib.js:48:8)
    at tryToString (fs.js:457:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:444:12)
Decompile ./pages/edit_moka/index.wxml...
error on ./pages/edit_moka/index.wxml
err:  Error: Empty str in prop
    at Error (native)
    at wxmlify (/usr/local/weixinapp/wuWxml.js:176:47)
    at elemToString (/usr/local/weixinapp/wuWxml.js:230:57)
    at doWxml (/usr/local/weixinapp/wuWxml.js:247:33)
    at tryWxml (/usr/local/weixinapp/wuWxml.js:264:3)
    at wu.get.code (/usr/local/weixinapp/wuWxml.js:308:23)
    at fs.readFile (/usr/local/weixinapp/wuLib.js:48:8)
    at tryToString (fs.js:457:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:444:12)
Decompile ./pages/hot/index.wxml...
error on ./pages/hot/index.wxml
err:  Error: Empty str in prop
    at Error (native)
    at wxmlify (/usr/local/weixinapp/wuWxml.js:176:47)
    at elemToString (/usr/local/weixinapp/wuWxml.js:230:57)
    at doWxml (/usr/local/weixinapp/wuWxml.js:247:33)
    at tryWxml (/usr/local/weixinapp/wuWxml.js:264:3)
    at wu.get.code (/usr/local/weixinapp/wuWxml.js:308:23)
    at fs.readFile (/usr/local/weixinapp/wuLib.js:48:8)
    at tryToString (fs.js:457:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:444:12)
Decompile ./pages/m/index.wxml...
error on ./pages/m/index.wxml
err:  Error: Empty str in prop
    at Error (native)
    at wxmlify (/usr/local/weixinapp/wuWxml.js:176:47)
    at elemToString (/usr/local/weixinapp/wuWxml.js:230:57)
    at doWxml (/usr/local/weixinapp/wuWxml.js:247:33)
    at tryWxml (/usr/local/weixinapp/wuWxml.js:264:3)
    at wu.get.code (/usr/local/weixinapp/wuWxml.js:308:23)
    at fs.readFile (/usr/local/weixinapp/wuLib.js:48:8)
    at tryToString (fs.js:457:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:444:12)
Decompile ./pages/mine/chat/index.wxml...
error on ./pages/mine/chat/index.wxml
err:  Error: Empty str in prop
    at Error (native)
    at wxmlify (/usr/local/weixinapp/wuWxml.js:176:47)
    at elemToString (/usr/local/weixinapp/wuWxml.js:230:57)
    at doWxml (/usr/local/weixinapp/wuWxml.js:247:33)
    at tryWxml (/usr/local/weixinapp/wuWxml.js:264:3)
    at wu.get.code (/usr/local/weixinapp/wuWxml.js:308:23)
    at fs.readFile (/usr/local/weixinapp/wuLib.js:48:8)
    at tryToString (fs.js:457:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:444:12)
Decompile ./pages/mine/index.wxml...
error on ./pages/mine/index.wxml
err:  Error: Empty str in prop
    at Error (native)
    at wxmlify (/usr/local/weixinapp/wuWxml.js:176:47)
    at elemToString (/usr/local/weixinapp/wuWxml.js:230:57)
    at doWxml (/usr/local/weixinapp/wuWxml.js:247:33)
    at tryWxml (/usr/local/weixinapp/wuWxml.js:264:3)
    at wu.get.code (/usr/local/weixinapp/wuWxml.js:308:23)
    at fs.readFile (/usr/local/weixinapp/wuLib.js:48:8)
    at tryToString (fs.js:457:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:444:12)
Decompile ./pages/mine/member/index.wxml...
error on ./pages/mine/member/index.wxml
err:  Error: Empty str in prop
    at Error (native)
    at wxmlify (/usr/local/weixinapp/wuWxml.js:176:47)
    at elemToString (/usr/local/weixinapp/wuWxml.js:230:57)
    at doWxml (/usr/local/weixinapp/wuWxml.js:247:33)
    at tryWxml (/usr/local/weixinapp/wuWxml.js:264:3)
    at wu.get.code (/usr/local/weixinapp/wuWxml.js:308:23)
    at fs.readFile (/usr/local/weixinapp/wuLib.js:48:8)
    at tryToString (fs.js:457:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:444:12)
Decompile ./pages/moka/index.wxml...
error on ./pages/moka/index.wxml
err:  Error: Empty str in prop
    at Error (native)
    at wxmlify (/usr/local/weixinapp/wuWxml.js:176:47)
    at elemToString (/usr/local/weixinapp/wuWxml.js:230:57)
    at doWxml (/usr/local/weixinapp/wuWxml.js:247:33)
    at tryWxml (/usr/local/weixinapp/wuWxml.js:264:3)
    at wu.get.code (/usr/local/weixinapp/wuWxml.js:308:23)
    at fs.readFile (/usr/local/weixinapp/wuLib.js:48:8)
    at tryToString (fs.js:457:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:444:12)
Decompile ./pages/notice/index.wxml...
error on ./pages/notice/index.wxml
err:  Error: Empty str in prop
    at Error (native)
    at wxmlify (/usr/local/weixinapp/wuWxml.js:176:47)
    at elemToString (/usr/local/weixinapp/wuWxml.js:230:57)
    at doWxml (/usr/local/weixinapp/wuWxml.js:247:33)
    at tryWxml (/usr/local/weixinapp/wuWxml.js:264:3)
    at wu.get.code (/usr/local/weixinapp/wuWxml.js:308:23)
    at fs.readFile (/usr/local/weixinapp/wuLib.js:48:8)
    at tryToString (fs.js:457:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:444:12)
Decompile ./pages/view_h/index.wxml...
error on ./pages/view_h/index.wxml
err:  Error: Empty str in prop
    at Error (native)
    at wxmlify (/usr/local/weixinapp/wuWxml.js:176:47)
    at elemToString (/usr/local/weixinapp/wuWxml.js:230:57)
    at doWxml (/usr/local/weixinapp/wuWxml.js:247:33)
    at tryWxml (/usr/local/weixinapp/wuWxml.js:264:3)
    at wu.get.code (/usr/local/weixinapp/wuWxml.js:308:23)
    at fs.readFile (/usr/local/weixinapp/wuLib.js:48:8)
    at tryToString (fs.js:457:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:444:12)
Decompile ./pages/view_v/index.wxml...
error on ./pages/view_v/index.wxml
err:  Error: Empty str in prop
    at Error (native)
    at wxmlify (/usr/local/weixinapp/wuWxml.js:176:47)
    at elemToString (/usr/local/weixinapp/wuWxml.js:230:57)
    at doWxml (/usr/local/weixinapp/wuWxml.js:247:33)
    at tryWxml (/usr/local/weixinapp/wuWxml.js:264:3)
    at wu.get.code (/usr/local/weixinapp/wuWxml.js:308:23)
    at fs.readFile (/usr/local/weixinapp/wuLib.js:48:8)
    at tryToString (fs.js:457:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:444:12)

/usr/local/weixinapp/node_modules/vm2/lib/main.js:218
			throw this._internal.Decontextify.value(e);
			^
ReferenceError: _C is not defined
    at vm.js:2:1
    at ContextifyScript.Script.runInContext (vm.js:35:29)
    at VM.run (/usr/local/weixinapp/node_modules/vm2/lib/main.js:212:72)
    at wu.get.code (/usr/local/weixinapp/wuWxss.js:127:16)
    at fs.readFile (/usr/local/weixinapp/wuLib.js:48:8)
    at tryToString (fs.js:457:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:444:12)
[root@VM_179_192_centos weixinapp]# 

作者看到这个异常 能看出是哪里解析出问题嘛？ 能否给我提供点解决思路，我发现自己想要适配解决这个wxapkg文件的问题好像还是蛮吃力的，不吝赐教

**Comment by qwerty472123** [comment]
可以找到对应throw，注释掉，看看输出缺了什么，从中找问题

**Comment by youbooks** [comment]
![_20180402211517](https://user-images.githubusercontent.com/17697229/38197492-fc9b210c-36ba-11e8-9fc5-f924efb8ce07.png)
控制台打印这信息，Error: Empty str in prop 和 ReferenceError: _C is not defined

**Comment by qwerty472123** [comment]
我知道...
_C找不到是因为它没有引用其他wxss的功能，将相关功能删去或者把_C置[]即可。
Empty str in prop表示有属性的值找不到可以找到对应throw，注释掉，看看输出的wxml缺了什么，从中找问题

**Comment by youbooks** [comment]
![qq 20180403013837](https://user-images.githubusercontent.com/17697229/38207337-fbe3bb46-36df-11e8-842f-38d298227ca5.png)
![qq 20180403013847](https://user-images.githubusercontent.com/17697229/38207346-050cce1a-36e0-11e8-87a7-db24aacb09bc.png)
处理empty str in prop这个问题，我根据作者的提示，找到wuWxml.js 文件找到对应代码，打印日志发现这个是 elem.v[v] 出来值是undefined,

**Comment by qwerty472123** [comment]
当然是因为undefined才会throw啊...晕
关键是哪个element的哪个attr是undefined？进一步的，是wxml在读取哪个片段的时候解释出来的attr是undefined？然后就能解决问题了啊。
经考虑本人是不会适配这些版本的 详见 #24 。除了那些原因外，还有一个就是我注意到<https://github.com/leo9960/wechat-app-unpack/>大概就是开始进行多版本适配的时候声明为“安全”闭源的，很可能这是tx或者别的什么的底线吧，为了更多人能看到这个项目的主要部分还是不适配为好。
所以不要追踪一下就来发一个问题了。简单通读一下<https://github.com/qwerty472123/wxappUnpacker/blob/master/DETAILS.md>，又不难，自己动手丰衣足食吧。
