### ISSUE TITLE
求助，小程序编译发生了一个新的错误

### ISSUE THREAD

**Issue by bitspring** [qwerty472123/wxappUnpacker#226]
报错如下，之前的小程序倒是可以用
/root/wxappUnpacker-master/node_modules/vm2/lib/main.js:214
			throw this._internal.Decontextify.value(e);
			^
vm.js:140
			});
			^

SyntaxError: Unexpected token }
    at new Script (vm.js:85:7)
    at VMScript.compile (/root/wxappUnpacker-master/node_modules/vm2/lib/main.js:80:20)
    at VM.run (/root/wxappUnpacker-master/node_modules/vm2/lib/main.js:208:52)
    at wu.get.code (/root/wxappUnpacker-master/wuJs.js:30:6)
    at ioLimit.runWithCb (/root/wxappUnpacker-master/wuLib.js:80:8)
    at agent (/root/wxappUnpacker-master/wuLib.js:54:14)
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:54:3)

**Comment by bitspring** [comment]
[1.zip](https://github.com/qwerty472123/wxappUnpacker/files/2950789/1.zip)

**Comment by bitspring** [comment]
附件在二楼

**Comment by lizier** [comment]
分包解包我也遇到这个问题了，有没有老哥出来帮下手。

**Comment by lizier** [comment]
@larack8

**Comment by 7423385** [comment]
解包问题 请联系QQ7423385

**Comment by showching** [comment]
参考 #200 
感谢作者！

**Comment by bitspring** [comment]
@showching 貌似我这个错误和你那个错误不太一样

**Comment by gudqs7** [comment]
@bitspring  是个问题我就能解决 https://github.com/gudqs7/wxappUnpacker
