### ISSUE TITLE
求助，编译出来的文件不对

### ISSUE THREAD

**Issue by yudiya** [qwerty472123/wxappUnpacker#229]
我安装这些依赖项的时候，都会提示：
npm WARN Invalid version: "0.3"

最后反编译得到的文件完全不对..比如没有页面js文件，多了许多几个html文件...

执行编译命令后出现的错误提示：
```
Saving files...
Unpack done.
Split app-service.js and make up configs & wxss & wxml & wxs...

D:\Program Files\Nox\Nox_share\OtherShare\wxappUnpacker-master\node_modules\vm2\lib\main.js:214
                        throw this._internal.Decontextify.value(e);
                        ^
SyntaxError: Unexpected token }
    at VMScript.compile (D:\Program Files\Nox\Nox_share\OtherShare\wxappUnpacker-master\node_modules\vm2\lib\main.js:80:20)
    at VM.run (D:\Program Files\Nox\Nox_share\OtherShare\wxappUnpacker-master\node_modules\vm2\lib\main.js:208:52)
    at wu.get.code (D:\Program Files\Nox\Nox_share\OtherShare\wxappUnpacker-master\wuJs.js:30:6)
    at ioLimit.runWithCb (D:\Program Files\Nox\Nox_share\OtherShare\wxappUnpacker-master\wuLib.js:80:8)
    at agent (D:\Program Files\Nox\Nox_share\OtherShare\wxappUnpacker-master\wuLib.js:54:14)
    at tryToString (fs.js:456:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:443:12)
[_1806387983_5.zip](https://github.com/qwerty472123/wxappUnpacker/files/2990782/_1806387983_5.zip)

```

**Comment by yudiya** [comment]
[_1806387983_5.zip](https://github.com/qwerty472123/wxappUnpacker/files/2990797/_1806387983_5.zip)

**Comment by MrLiandMissLi** [comment]
同问

**Comment by 7423385** [comment]
请联系QQ7423385

**Comment by yudiya** [comment]
谢谢！
不过我之前付费找人帮忙弄了..

> 请联系QQ7423385

**Comment by gudqs7** [comment]
https://github.com/gudqs7/wxappUnpacker
这种大概是有小程序依赖了插件, 我有遇到过, 我这边处理了, 试试

**Comment by gudqs7** [comment]
> _1806387983_5.zip

https://github.com/gudqs7/wxappUnpacker
这种大概是有小程序依赖了插件, 我有遇到过, 我这边处理了, 试试
