### ISSUE TITLE
反编辑缺少wxss文件，求解决

### ISSUE THREAD

**Issue by zhouzongyu** [qwerty472123/wxappUnpacker#240]
ReferenceError: __vd_version_info__ is not defined
    at vm.js:3:7
    at ContextifyScript.Script.runInContext (vm.js:32:29)
[_-1760009094_13.zip](https://github.com/qwerty472123/wxappUnpacker/files/3093409/_-1760009094_13.zip)
3)

**Comment by 7423385** [comment]
联系QQ 7423385

**Comment by gudqs7** [comment]
@zhouzongyu  试试 https://github.com/gudqs7/wxappUnpacker

**Comment by Robertzewen** [comment]
@gudqs7 非常感谢，解决了
