### ISSUE TITLE
反编辑缺少wxss文件，求解决

### ISSUE THREAD

**Issue by lcs-plus** [qwerty472123/wxappUnpacker#241]
ReferenceError: __vd_version_info__ is not defined
    at vm.js:3:3
    at Script.runInContext (vm.js:107:20)

**Comment by 7423385** [comment]
联系qq 7423385

**Comment by gudqs7** [comment]
@lcs-plus  试试 https://github.com/gudqs7/wxappUnpacker

**Comment by IHongTaoI** [comment]
@gudqs7 推荐用这个人的  https://github.com/gudqs7/wxappUnpacker

**Comment by lcs-plus** [comment]
感想




------------------ 原始邮件 ------------------
发件人: "洪涛"<notifications@github.com>; 
发送时间: 2019年4月27日(星期六) 晚上6:05
收件人: "qwerty472123/wxappUnpacker"<wxappUnpacker@noreply.github.com>; 
抄送: "星雨"<2968078420@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [qwerty472123/wxappUnpacker] 反编辑缺少wxss文件，求解决 (#241)




@gudqs7 推荐用这个人的  https://github.com/gudqs7/wxappUnpacker

**Comment by kerwingo** [comment]
@gudqs7删掉了哦

**Comment by a395027720** [comment]
修改wxappUnpacker文件中的 wuWxss.js
`
function runVM(name, code) {
// let wxAppCode = {}, handle = {cssFile: name};
// let vm = new VM({
// sandbox: Object.assign(new GwxCfg(), {
// __wxAppCode__: wxAppCode,
// setCssToHead: cssRebuild.bind(handle)
// })
// });
// vm.run(code);
// for (let name in wxAppCode) if (name.endsWith(".wxss")) {
// handle.cssFile = path.resolve(frameName, "..", name);
// wxAppCode[name]();
// }
let wxAppCode = {};
let handle = {cssFile: name};
let gg = new GwxCfg();
let tsandbox = {
$gwx: GwxCfg.prototype["$gwx"],
__mainPageFrameReady__: GwxCfg.prototype["$gwx"], //解决 $gwx is not defined
__vd_version_info__: GwxCfg.prototype["$gwx"], //解决 __vd_version_info__ is not defined
__wxAppCode__: wxAppCode,
setCssToHead: cssRebuild.bind(handle)
}
let vm = new VM({sandbox: tsandbox});
vm.run(code);
for (let name in wxAppCode) {
if (name.endsWith(".wxss")) {
handle.cssFile = path.resolve(frameName, "..", name);
wxAppCode[name]();
}
}
}
`
