### ISSUE TITLE
大神请帮我看看这个

### ISSUE THREAD

**Issue by bg1dx** [qwerty472123/wxappUnpacker#242]
链接：https://pan.baidu.com/s/1asP19aeP8jJ7aedY0RhpTQ 
提取码：ea7y 
复制这段内容后打开百度网盘手机App，操作更方便哦

主包解开了 自包提示错误
Unpack done.
C:\Users\bh1uvs\Desktop\wxappUnpacker-master\wuWxapkg.js:104
        }else throw Error("This package is unrecognizable.\nMay be this package is a subPackage which should be unpacked with -s=<MainDir>.\nOtherwise, please decrypted every type of file by hand.")
              ^

Error: This package is unrecognizable.
May be this package is a subPackage which should be unpacked with -s=<MainDir>.
Otherwise, please decrypted every type of file by hand.
    at Array.packDone (C:\Users\bh1uvs\Desktop\wxappUnpacker-master\wuWxapkg.js:104:14)
    at CntEvent.decount (C:\Users\bh1uvs\Desktop\wxappUnpacker-master\wuLib.js:17:43)
    at ioLimit.runWithCb.err (C:\Users\bh1uvs\Desktop\wxappUnpacker-master\wuLib.js:73:11)
    at agent (C:\Users\bh1uvs\Desktop\wxappUnpacker-master\wuLib.js:54:14)
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)

我用的命令：node wuWxapkg.js -d -s=./pkg/_-1014527539_11 ./pkg/_1123949441_213.wxapkg
我的命令不知道是否正确，求解

**Comment by 7423385** [comment]
联系QQ 7423385

**Comment by gudqs7** [comment]
> 链接：https://pan.baidu.com/s/1asP19aeP8jJ7aedY0RhpTQ
> 提取码：ea7y
> 复制这段内容后打开百度网盘手机App，操作更方便哦
> 
> 一个小程序有两个包 其中一个解开了 另外一个大的 解包提示这个
> Unpack done.
> C:\Users\bh1\Desktop\wxappUnpacker-master\wuWxapkg.js:104
> }else throw Error("This package is unrecognizable.\nMay be this package is a subPackage which should be unpacked with -s=.\nOtherwise, please decrypted every type of file by hand.")
> ^
> 
> Error: This package is unrecognizable.
> May be this package is a subPackage which should be unpacked with -s=.
> Otherwise, please decrypted every type of file by hand.
> at Array.packDone (C:\Users\bh1\Desktop\wxappUnpacker-master\wuWxapkg.js:104:14)
> at CntEvent.decount (C:\Users\bh1\Desktop\wxappUnpacker-master\wuLib.js:17:43)
> at ioLimit.runWithCb.err (C:\Users\bh1\Desktop\wxappUnpacker-master\wuLib.js:73:11)
> at agent (C:\Users\bh1\Desktop\wxappUnpacker-master\wuLib.js:54:14)
> at FSReqWrap.args [as oncomplete] (fs.js:140:20)
> 
> 我用的命令：node wuWxapkg.js -d -s=./pkg/_-1014527539_11 ./pkg/_1123949441_213.wxapkg
> 我的命令不知道是否正确，求解

how about try  https://github.com/gudqs7/wxappUnpacker

**Comment by gudqs7** [comment]
@bg1dx 试试  https://github.com/gudqs7/wxappUnpacker, 不行联系我

**Comment by cuimin520** [comment]
@gudqs7 大神 你这个试过了 就是在解析分包的时候 wxss 到保存不到主包目录里 出现一个空文件，但是在分包里却有这个CSS样式  打开就是  这样 ：/* xxx/pages/xxxx/xxxxx/index.wxss */  其他JS文件都能正常到指定目录

**Comment by 2103539816** [comment]
付费解决解包过程中的任何问题，需要请联系QQ7423385
