### ISSUE TITLE
请问这个报错哪位大哥能解决一下wuLib.js:86 if (err) throw Error("Save file error: " + err);

### ISSUE THREAD

**Issue by githubxl77** [qwerty472123/wxappUnpacker#244]
wuLib.js:86
        if (err) throw Error("Save file error: " + err);
![1556194496(1)](https://user-images.githubusercontent.com/42185725/56734987-e4a0a780-6796-11e9-8105-5acb130f8d2a.jpg)

**Comment by gudqs7** [comment]
> wuLib.js:86
> if (err) throw Error("Save file error: " + err);
> ![1556194496(1)](https://user-images.githubusercontent.com/42185725/56734987-e4a0a780-6796-11e9-8105-5acb130f8d2a.jpg)

这个简单, 因为 引入了第三方插件 , 所有路径含有 plugin:      然而 windows 路径:是分隔符啊, 这个最简单就是用 Linux 解决

**Comment by 7423385** [comment]
联系QQ7423385

**Comment by gudqs7** [comment]
> 联系QQ7423385

@7423385  你是魔鬼吗

**Comment by gudqs7** [comment]
@githubxl77

**Comment by CerryWong** [comment]
@gudqs7 linux上报的是另外的错误~

> vm.js:176
			});
			^
SyntaxError: Unexpected token }
    at VMScript.compile (/root/wxappUnpacker-0.3/node_modules/vm2/lib/main.js:80:20)
    at VM.run (/root/wxappUnpacker-0.3/node_modules/vm2/lib/main.js:215:10)
    at wu.get.code (/root/wxappUnpacker-0.3/wuJs.js:30:6)
    at ioLimit.runWithCb (/root/wxappUnpacker-0.3/wuLib.js:80:8)
    at agent (/root/wxappUnpacker-0.3/wuLib.js:54:14)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)

@githubxl77  兄dei~你的问题解决了吗？

**Comment by 2103539816** [comment]
付费解决解包过程中的任何问题，需要请联系QQ7423385

**Comment by xiaolingogogo** [comment]
> @gudqs7 linux上报的是另外的错误~
> 
> > vm.js:176
> > });
> > ^
> > SyntaxError: Unexpected token }
> > at VMScript.compile (/root/wxappUnpacker-0.3/node_modules/vm2/lib/main.js:80:20)
> > at VM.run (/root/wxappUnpacker-0.3/node_modules/vm2/lib/main.js:215:10)
> > at wu.get.code (/root/wxappUnpacker-0.3/wuJs.js:30:6)
> > at ioLimit.runWithCb (/root/wxappUnpacker-0.3/wuLib.js:80:8)
> > at agent (/root/wxappUnpacker-0.3/wuLib.js:54:14)
> > at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
> 
> @githubxl77 兄dei~你的问题解决了吗？

我也遇到这个问题了，你解决了吗？
