### ISSUE TITLE
反编译错误

### ISSUE THREAD

**Issue by RamboY5** [qwerty472123/wxappUnpacker#248]
ReferenceError: __vd_version_info__ is not defined
    at vm.js:3:3
    at ContextifyScript.Script.runInContext (vm.js:59:29)
    at VM.run (D:\Rambo\study\unpack\wxappUnpacker-master\node_modules\vm2\lib\main.js:217:72)
    at runVM (D:\Rambo\study\unpack\wxappUnpacker-master\wuWxss.js:69:6)
    at runOnce (D:\Rambo\study\unpack\wxappUnpacker-master\wuWxss.js:86:27)
    at Array.preRun (D:\Rambo\study\unpack\wxappUnpacker-master\wuWxss.js:166:5)
    at CntEvent.decount (D:\Rambo\study\unpack\wxappUnpacker-master\wuLib.js:17:43)
    at ioLimit.runWithCb (D:\Rambo\study\unpack\wxappUnpacker-master\wuLib.js:81:11)
    at agent (D:\Rambo\study\unpack\wxappUnpacker-master\wuLib.js:54:14)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)

**Comment by RamboY5** [comment]
没有大佬们知道为啥会出这个错误咩

**Comment by 7423385** [comment]
联系QQ 7423385

**Comment by gudqs7** [comment]
> 没有大佬们知道为啥会出这个错误咩

我猜那个包依赖了 插件
@RamboY5  看看这个 https://github.com/gudqs7/wxappUnpacker

**Comment by zsycomeon** [comment]
@gudqs7  真大佬

**Comment by 379682421** [comment]
> > 没有大佬们知道为啥会出这个错误咩
> 
> 我猜那个包依赖了 插件
> @RamboY5 看看这个 https://github.com/gudqs7/wxappUnpacker

大佬，报console is not defined怎么解决啊~

**Comment by 2103539816** [comment]
付费解决解包过程中的任何问题，需要请联系QQ7423385

**Comment by gadfly0x** [comment]
test
