### ISSUE TITLE
解析出现.wxml.ori.js文件 ReferenceError: _C is not defined     at vm.js:2:1

### ISSUE THREAD

**Issue by kakaxi114** [qwerty472123/wxappUnpacker#26]
node_modules\vm2\lib\main.js:218
                        throw this._internal.Decontextify.value(e);
                        ^
ReferenceError: _C is not defined
    at vm.js:2:1
    at ContextifyScript.Script.runInContext (vm.js:59:29)
    at VM.run (D:\moban\xcx6\node_modules\vm2\lib\main.js:212:72)
    at wu.get.code (D:\moban\xcx6\wuWxss.js:127:16)
    at fs.readFile (D:\moban\xcx6\wuLib.js:48:8)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)

**Comment by kakaxi114** [comment]
文件：链接: https://pan.baidu.com/s/13oOwNGWrKog-tXl2saw5LQ 密码: yrty
