### ISSUE TITLE
wxml解析不了，ReferenceError: x is not defined

### ISSUE THREAD

**Issue by kakaxi114** [qwerty472123/wxappUnpacker#27]
node_modules\vm2\lib\main.js:218
                        throw this._internal.Decontextify.value(e);
                        ^
ReferenceError: x is not defined
    at vm.js:1764:10
    at ContextifyScript.Script.runInContext (vm.js:59:29)
    at VM.run (D:\moban\xcx6\node_modules\vm2\lib\main.js:212:72)
    at wu.get.code (D:\moban\xcx6\wuWxml.js:294:7)
    at fs.readFile (D:\moban\xcx6\wuLib.js:48:8)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)

链接: https://pan.baidu.com/s/1s-4X4yokqUlo1lf86gq1ow 密码: pdap
辛苦看看

**Comment by qwerty472123** [comment]
你这个版本是`v0.6vv_20170911_fbi_wxs`
很抱歉我不会对旧版本进行适配更新旧版本
见 #19 #21 #24
