### ISSUE TITLE
反编译失败

### ISSUE THREAD

**Issue by beasonshu** [qwerty472123/wxappUnpacker#270]
Unpack file /Users/user/Desktop/_1123949441_242.wxapkg.tar...

Header info:
  firstMark: 0x5f
  unknownInfo:  825307699
  infoListLength:  959723828
  dataLength:  875650866
  lastMark: 0x34
/Users/user/Downloads/wxappUnpacker/wuWxapkg.js:20
	if(firstMark!=0xbe||lastMark!=0xed)throw Error("Magic number is not correct!");
	                                   ^

Error: Magic number is not correct!
    at header (/Users/user/Downloads/wxappUnpacker/wuWxapkg.js:20:43)
    at wu.get.buf (/Users/user/Downloads/wxappUnpacker/wuWxapkg.js:111:35)
    at ioLimit.runWithCb (/Users/user/Downloads/wxappUnpacker/wuLib.js:80:8)
    at agent (/Users/user/Downloads/wxappUnpacker/wuLib.js:54:14)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)

**Comment by sky861421718163** [comment]
同问

**Comment by weituotian** [comment]
同问

**Comment by shadow-keimi** [comment]
同，求解

**Comment by qingnichitudou** [comment]
同，求解

**Comment by qwerty472123** [comment]
你这个是tar文件，根本不是wxapkg文件吧...
