### ISSUE TITLE
Save file error

### ISSUE THREAD

**Issue by chanalonwon** [qwerty472123/wxappUnpacker#273]
程序执行错误信息

```
F:\wxapp\wxappUnpacker-master\wxappUnpacker-master\wuLib.js:72
                if(err)throw Error("Save file error: "+err);
                       ^

Error: Save file error: Error: ENOENT: no such file or directory, open 'F:\wxapp\wxapkg\_858013428_40\pages\index\plugin:\wx104a1a20c3f81ec2\cell.json'
    at ioLimit.runWithCb.err (F:\wxapp\wxappUnpacker-master\wxappUnpacker-master\wuLib.js:72:16)
    at agent (F:\wxapp\wxappUnpacker-master\wxappUnpacker-master\wuLib.js:54:14)
    at fs.open (fs.js:1174:7)
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
```

**Comment by uchaopin** [comment]
大哥 拟解决了么

**Comment by rhsy445566** [comment]
> 程序执行错误信息
> 
> ```
> F:\wxapp\wxappUnpacker-master\wxappUnpacker-master\wuLib.js:72
>                 if(err)throw Error("Save file error: "+err);
>                        ^
> 
> Error: Save file error: Error: ENOENT: no such file or directory, open 'F:\wxapp\wxapkg\_858013428_40\pages\index\plugin:\wx104a1a20c3f81ec2\cell.json'
>     at ioLimit.runWithCb.err (F:\wxapp\wxappUnpacker-master\wxappUnpacker-master\wuLib.js:72:16)
>     at agent (F:\wxapp\wxappUnpacker-master\wxappUnpacker-master\wuLib.js:54:14)
>     at fs.open (fs.js:1174:7)
>     at FSReqWrap.args [as oncomplete] (fs.js:140:20)
> ```

解决了嘛？怎么解决的？
