### ISSUE TITLE
wxml无法解析 err:  Error: Unknown expression callee name _af

### ISSUE THREAD

**Issue by 81pla** [qwerty472123/wxappUnpacker#28]
程序执行命令(可选):

node wuWxml.js -m /Users/duke/Downloads/wxappUnpacker-0.2/unpack/page-frame.html 

程序执行错误信息(如果反馈是抛出异常的错误，必填):

```
Decompile ./dreamfy/kefu.wxml...
error on ./dreamfy/kefu.wxml
err:  Error: Unknown expression callee name _af
    at analyze (/Users/duke/Downloads/wxappUnpacker-0.2/wuWxml.js:61:22)
    at doWxml (/Users/duke/Downloads/wxappUnpacker-0.2/wuWxml.js:254:3)
    at tryWxml (/Users/duke/Downloads/wxappUnpacker-0.2/wuWxml.js:264:3)
    at wu.get.code (/Users/duke/Downloads/wxappUnpacker-0.2/wuWxml.js:308:23)
    at fs.readFile (/Users/duke/Downloads/wxappUnpacker-0.2/wuLib.js:48:8)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
Decompile ./dreamfy/myindex-list.wxml...
error on ./dreamfy/myindex-list.wxml
err:  Error: Unknown expression callee name _af
    at analyze (/Users/duke/Downloads/wxappUnpacker-0.2/wuWxml.js:61:22)
    at anaRecursion (/Users/duke/Downloads/wxappUnpacker-0.2/wuWxml.js:10:10)
    at analyze (/Users/duke/Downloads/wxappUnpacker-0.2/wuWxml.js:43:10)
    at doWxml (/Users/duke/Downloads/wxappUnpacker-0.2/wuWxml.js:254:3)
    at tryWxml (/Users/duke/Downloads/wxappUnpacker-0.2/wuWxml.js:264:3)
    at wu.get.code (/Users/duke/Downloads/wxappUnpacker-0.2/wuWxml.js:308:23)
    at fs.readFile (/Users/duke/Downloads/wxappUnpacker-0.2/wuLib.js:48:8)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)

```

程序包(你所要解压的程序包地址, 可为网盘链接, 也可直接上传[上传前请先打包]. 必填):
链接: https://pan.baidu.com/s/1Y4DMNctdexkEGlsYT4f7ug 密码: dbax

其他附加内容:
只有wxml出现错误，其他没错误  辛苦大神了

**Comment by 81pla** [comment]
window.__wcc_version__='v0.6vv_20180125_fbi'

**Comment by 81pla** [comment]
更新：之前使用的release版本   下载master分支 可以解释出来了  可以用

**Comment by qwerty472123** [comment]
本程序对_af的行为可能有偏差，如有遇到欢迎指出
