### ISSUE TITLE
直接解包小程序报错

### ISSUE THREAD

**Issue by kkkio2** [qwerty472123/wxappUnpacker#32]
程序执行命令(可选): node wuWxapkg.js ../wechat/_-1140523515_1.wxapkg

程序执行错误信息(如果反馈是抛出异常的错误，必填):

```
{ name: '/wxParse/wxParse.html', off: 391059, size: 284 }
{ name: '/page-frame.html', off: 391343, size: 340317 }
Saving files...
Unpack done.
Split app-service.js and make up configs & wxss & wxml & wxs...
Splitting "/data/webapp/wechat/wechat/_-1140523515_1/app-service.js" done.

/usr/local/lib/node_modules/vm2/lib/main.js:218
			throw this._internal.Decontextify.value(e);
			^
ReferenceError: x is not defined
    at vm.js:7205:10
    at Script.runInContext (vm.js:74:29)
    at VM.run (/usr/local/lib/node_modules/vm2/lib/main.js:212:72)
    at wu.get.code (/data/webapp/wechat/wxappUnpacker/wuWxml.js:294:7)
    at fs.readFile (/data/webapp/wechat/wxappUnpacker/wuLib.js:48:8)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:525:3)

```

程序结果错误信息(如果反馈不是抛出异常的错误, 必填, 请尽可能详细描述):
不懂node，没法反馈了
程序包(你所要解压的程序包地址, 可为网盘链接, 也可直接上传[上传前请先打包]. 必填):
[测试小程序](https://github.com/qwerty472123/wxappUnpacker/files/1910455/_-1140523515_1.wxapkg.zip)

**Comment by qwerty472123** [comment]
又一个
旧有版本(`v0.6vv_20170919_fbi_wxs`)不提供兼容性支持
见(局限1 #19 #21 #24 #26 #27 #31)
