### ISSUE TITLE
带插件的小程序包无法解插件部分

### ISSUE THREAD

**Issue by xjd1123** [qwerty472123/wxappUnpacker#35]
带插件的小程序包无法解插件部分
[9.zip](https://github.com/qwerty472123/wxappUnpacker/files/1926898/9.zip)

**Comment by qwerty472123** [comment]
插件在这个包内找不到
找找同时放着的别的包看看

**Comment by xjd1123** [comment]
sudu8_page为主程序，其他插件sudu8_page_plugin_exchange 、sudu8_page_plugin_food 、sudu8_page_plugin_pt、sudu8_page_plugin_share、sudu8_page_plugin_sign都解不出文件。

**Comment by qwerty472123** [comment]
我认为很可能插件和分包类似，插件部分会保存在手机的其他位置，能否帮忙找找`/data/data/com.tencent.mm/MicroMsg/{User}/appbrand/pkg`附近的位置有没有相关内容呢。
我认为包文件加密的可能性不大(毕竟其他部分都是明文)，而从我在wxapkg这个二进制文件内查找`sudu8_page_plugin_food`等字样的结果看起来很可能这部分代码不在这个文件内。

**Comment by qwerty472123** [comment]
看另一个例子 #34 中的`app-config.js`（解包时用`-d`保留）中的subPackages项，可以证明插件和分包用了同一种底层实现方式，即插件内容存在于其他wxapkg文件在

**Comment by xjd1123** [comment]
明天我抓新的包给你看看，可能是小程序开发者做了限制。

**Comment by xjd1123** [comment]
已经抓包主程序和插件缓存包！

**Comment by xjd1123** [comment]
[dati.zip](https://github.com/qwerty472123/wxappUnpacker/files/1938398/dati.zip)
另一个插件样本！

**Comment by qwerty472123** [comment]
@xjd1123 十分感谢这些样本，不过调整我的程序还有再要过一段的时间
有需要可以用命令手动解开wxml等
目前的考虑：空的json/wxss文件默认改为不输出（被应用的除外）、`插件`暂时以按分包的形式输出
、应支持在同一文件夹下自动寻找分包、分包本身的自动解码+提示功能、把自动进行各个操作的js独立出`wuWxapkg.js`

**Comment by a5108** [comment]
@xjd1123  大佬这是在解密万能门店啊 6666

**Comment by xjd1123** [comment]
提供新样本进行分包解析！
[分包样本一.zip](https://github.com/qwerty472123/wxappUnpacker/files/2064551/default.zip)
[分包样本二.zip](https://github.com/qwerty472123/wxappUnpacker/files/2064552/default.zip)

**Comment by qwerty472123** [comment]
@a5108
分析出来的是什么…
半手工分析出某个分包的内容？就应其他几个命令手工搞一下大家都知道。
还是自动寻找分包编号？这个没研究过

**Comment by xjd1123** [comment]
已找到解决方案，可以删除此贴了。用网上流传的全自动解密exe解分包里面的js和wxss。用你的工具node wuWxml.js xxx.wxapkg解出wxml，一起合并下就还原出了。麻烦了点，但还是可以的。上面那个应该是打广告！

**Comment by qwerty472123** [comment]
@xjd1123
手动解法 用我的node wuWxss.js等也可以
本帖一直开着是计划哪天有空实现一下自动识别和解包，留着作为提醒…

**Comment by qwerty472123** [comment]
据 #75 报告 入口wxml也可能处于分包内

**Comment by andy388** [comment]
发现反编译出来的小程序代码都很乱不能运行，，特别是大于2m的包编译不出来，目录结构发生了变化

**Comment by qwerty472123** [comment]
@andy388 可以给个样例 指出什么地方很乱吗
顺便JS乱是没救的，调一下是可以运行

**Comment by qwerty472123** [comment]
@andy388 可以给个样例吗 你这样说我无法分析...

**Comment by andy388** [comment]
经过测试发现只要一个小程序2个+以上的wxapkg包，都不行了。数据不完整我不知道怎么这里给你看那个wxapkg，我企鹅：1738885251

**Comment by qwerty472123** [comment]
@andy388 直接修改扩展名或打包压缩后拖拽上传 或 留一个百度盘的连接等方式都可以
你可以看看本页面下的几个分包，你试着解包下和你说的情况是否相同，而本页面上的分包其实都是可以半手动解包的 具体解包方法见 #85

**Comment by BartSu** [comment]
这个小程序一共有两个包，分包里面都是js文件，很多WA开头，用WuWxml， WuWxss都编译不出wxss，看了另外一个issue，是不是里面好像这个有个worker的线程，现在还不支持来着。
[drawing.zip](https://github.com/qwerty472123/wxappUnpacker/files/2109165/drawing.zip)

**Comment by qwerty472123** [comment]
@BartSu 
1. 如有疑问，并且不是和某个主题特别相关（或不确定）请新开一个 issue，否则会打扰其他人，也会使得这个issue显得非常混乱。
2. 你给的 _-1209795170_14 属于版本过低 `v0.6vv_20170911_fbi_wxs` 是issus_template 中明确不支持的版本。
3. 你给的另一个包属于引擎/框架包，用来支持选用特定版本的微信小程序/游戏运行，而不属于任何一个小程序/游戏。

**Comment by qwerty472123** [comment]
https://developers.weixin.qq.com/minigame/dev/tutorial/base/subpackages.html
小游戏也有分包了.....

**Comment by andy388** [comment]
链接：https://pan.baidu.com/s/14ofyj1Q9mf1vfF9OeEp1mQ 密码：jzzt我就下这2个包编译出来好像不行你看看啥情况

**Comment by wbcz** [comment]
对于分包的小程序，在执行node wuWxml.js page-frame.html的时候，报错unweapp/wxapkg/102.wxapkg_unpacked/node_modules/vm2/lib/main.js:210
			throw this._internal.Decontextify.value(e);
			^
ReferenceError: x is not defined
这个是否是其他包为引入到主包引起的呢

**Comment by wbcz** [comment]
已经解决了，谢谢！

**Comment by yorick520** [comment]
@wbcz 你这个unweapp/wxapkg/102.wxapkg_unpacked/node_modules/vm2/lib/main.js:210
问题是如何解决的？求教

**Comment by jackzhangsir** [comment]
@qwerty472123 你好，我有一个包，解出来之后都没有wxml文件，其他的JS、json、wxss都有。

方便帮忙看下吗？
[链接: https://pan.baidu.com/s/1-5O6HHOXqKu79CLnEdY31g ](url)
密码: c3bq

**Comment by qwerty472123** [comment]
@jackzhangsir 版本过低，本项目不予支持

**Comment by jackzhangsir** [comment]
@qwerty472123 那低版本能否手动解page-frame.html文件呢，我提供的apkg没有办法可以解开吗？

**Comment by qwerty472123** [comment]
@jackzhangsir 所有的包当然都是可以手动解的
但这里的手动包括改我的脚本或者自己写脚本

**Comment by xianhaosui** [comment]
也遇到210错误了

**Comment by qwerty472123** [comment]
@xianhaosui 老版本不支持 错的不是`vm.run`而是老版本生成的js内容不同 本项目使用的字符串匹配截取有用内容失败
请勿再在issue下回复与该issue无关的内容。

**Comment by yixuancc** [comment]
@qwerty472123  大佬，小程序分包怎么手动解包，小白求教！

**Comment by tonghaiping** [comment]
var m0=function(e,s,r,gg){
var z=gz$gwx_1()
var oB=_n('view')
_rz(z,oB,'class',0,e,s,gg)
var xC=_n('view')
_rz(z,xC,'class',1,e,s,gg)
var oD=_n('image')
_rz(z,oD,'src',2,e,s,gg)
_(xC,oD)
_(oB,xC)
var fE=_n('view')
_rz(z,fE,'class',3,e,s,gg)
var cF=_oz(z,4,e,s,gg)
_(fE,cF)
_(oB,fE)
_(r,oB)
return r
}
这种格式的page_frame应该怎么解包啊

**Comment by xjd1123** [comment]
贴出你的小程序抓包缓存文件来啊！

**Comment by tonghaiping** [comment]
我解析wxml文件，手动解包不对，不太了解这个function的调用参数方式，求教。
百度网盘地址：https://pan.baidu.com/s/1tcx6sglbGK75muSUhTleDw 
无密码

**Comment by dinghangxing** [comment]
@qwerty472123  大牛  我这个包用node wuWxapkg.js 解包的时候报throw this._internal.Decontextify.value(e) ；解出的page-frame.html等用命令也是解不出；求指点。链接：https://pan.baidu.com/s/15b2hzOHXIUGJbGThbz72oA 
提取码：nr98

**Comment by dinghangxing** [comment]
> dinghangxing 已经帮你解出来了，邮箱发我，我发你！
62889614@qq.com   谢谢

**Comment by xjd1123** [comment]
dinghangxing，麻烦做事仔细点靠谱点，你这个邮箱错误！

**Comment by dinghangxing** [comment]
> dinghangxing，麻烦做事仔细点靠谱点，你这个邮箱错误！
不好意思   dhangxing@163.com   您试试发我这个邮箱   谢谢了

**Comment by zhouliangjin1990** [comment]
@xjd1123 下面的小程序包反编译出错，大神帮忙处理一下，百度网盘链接：https://pan.baidu.com/s/1WZk5dc62KibiNxuG93v9HQ
无提取密码

**Comment by xjd1123** [comment]
zhouliangjin1990 带插件的，不解！

**Comment by jpdan** [comment]
@xjd1123 分包小程序反编译报错
![image](https://user-images.githubusercontent.com/3361732/49793024-1fb5b780-fd6f-11e8-8856-f03268200724.png)
链接: https://pan.baidu.com/s/1AQYNtZ4gB0uZBSAk0RzmKg 
提取码: ipqe

**Comment by zlovex** [comment]
![_20190109114809](https://user-images.githubusercontent.com/24222470/50875964-a4930000-1405-11e9-9504-93eafd2f86f4.png)
@qwerty472123  您好！这个是包不完整还是什么情况？谢谢！

**Comment by 7423385** [comment]
QQ7423385 分包能解 成功后付费

**Comment by COCSTang** [comment]
我们员工电脑丢了 代码没有提交SVN  麻烦大神 帮忙加压我们的小程序的最新发布源码 
[code.zip](https://github.com/qwerty472123/wxappUnpacker/files/3129886/code.zip)

**Comment by xianhaosui** [comment]
@COCSTang你这个办法好




------------------ 原始邮件 ------------------
发件人: "COCSTang"<notifications@github.com>; 
发送时间: 2019年4月30日(星期二) 中午11:41
收件人: "qwerty472123/wxappUnpacker"<wxappUnpacker@noreply.github.com>; 
抄送: "爬上繁星"<842630388@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [qwerty472123/wxappUnpacker] 提供对小程序分包的支持 (#35)




我们员工电脑丢了 代码没有提交SVN  麻烦大神 帮忙加压我们的小程序的最新发布源码
 code.zip

**Comment by allenzhouzhou** [comment]
有子目录，子目录解出只有.json
求是怎么回事
![image](https://user-images.githubusercontent.com/5652405/60162993-4039f080-982d-11e9-90e4-6c4965e408ea.png)


![image](https://user-images.githubusercontent.com/5652405/60162964-32846b00-982d-11e9-8e47-78455fc983ec.png)

-

**Comment by ihtvr** [comment]
链接：https://pan.baidu.com/s/1G6K0k9gIBaUWreKgn_Un4Q 
提取码：24i8 
网盘，求解...

Error: This package is unrecognizable.
May be this package is a subPackage which should be unpacked with -s=<MainDir>.
Otherwise, please decrypted every type of file by hand.
    at Error (native)
    at Array.packDone (D:\workspace\wxappUnpacker-master\wuWxapkg.js:104:14)
    at CntEvent.decount (D:\workspace\wxappUnpacker-master\wuLib.js:17:43)
    at ioLimit.runWithCb.err (D:\workspace\wxappUnpacker-master\wuLib.js:73:11)
    at agent (D:\workspace\wxappUnpacker-master\wuLib.js:54:14)
    at FSReqWrap.oncomplete (fs.js:123:15)
