### ISSUE TITLE
node wuWxss.js page-frame.html  出错

### ISSUE THREAD

**Issue by jike-org** [qwerty472123/wxappUnpacker#39]
程序执行命令(可选):
node wuWxss.js page-frame.html

程序执行错误信息(如果反馈是抛出异常的错误，必填):

```
Desktop/wxappUnpacker/wuLib.js:96
			if(err)throw Error("Scan dir error: "+err);
			       ^

Error: Scan dir error: Error: ENOTDIR: not a directory, scandir 'page-frame.html'
    at ioLimit.runWithCb (/Desktop/wxappUnpacker/wuLib.js:96:17)
    at agent (/Desktop/wxappUnpacker/wuLib.js:54:14)
```

**Comment by qwerty472123** [comment]
该命令的参数为文件夹…
