### ISSUE TITLE
你好，求教！还原wxss的步骤出现错误

### ISSUE THREAD

**Issue by soloooooo** [qwerty472123/wxappUnpacker#4]
`Guess wxss(first turn) done.
Generate wxss(second turn)...
/Users/zhufeng/node_modules/vm2/lib/main.js:218
			throw this._internal.Decontextify.value(e);
			^

TypeError: Cannot read property '0' of undefined
    at Object.toDir (/Users/zhufeng/wuLib.js:79:7)
    at makeup (/Users/zhufeng/wuWxss.js:22:81)
    at makeup (/Users/zhufeng/wuWxss.js:34:15)
    at makeup (/Users/zhufeng/wuWxss.js:34:15)
    at /Users/zhufeng/wuWxss.js:42:20
    at Object.apply (/Users/zhufeng/node_modules/vm2/lib/contextify.js:288:34)
    at vm.js:1:22
    at ContextifyScript.Script.runInContext (vm.js:59:29)
    at VM.run (/Users/zhufeng/node_modules/vm2/lib/main.js:212:72)
    at runVM (/Users/zhufeng/wuWxss.js:47:5)
`

**Comment by qwerty472123** [comment]
似乎是有个被引用的wxss找不到来源，可以发一下你解包的 wxapkg 吗

**Comment by qwerty472123** [comment]
@soloooooo 已经增强了wxss的容错性，找不到的时候会强制指定一个来源。
不过可以的话，还是希望看一下你的样本。

**Comment by soloooooo** [comment]
- 感谢！更新之后能成功还原了，这是那个wxapkg
[_-710220512_15.wxapkg.zip](https://github.com/qwerty472123/wxappUnpacker/files/1831795/_-710220512_15.wxapkg.zip)

**Comment by qwerty472123** [comment]
针对这个 wxapkg 将还原 wxss 的代码继续完善了一部分。（对引用计数小于2的干脆不要来源，直接将引用内容复制进去）

**Comment by zhq426** [comment]
这个解压失败了, 麻烦帮忙看下为什么... 谢谢
链接：https://pan.baidu.com/s/1w9H5ccnb7C6gtRD2Odd0ag 
提取码：n68b

**Comment by yunShare** [comment]
此问题已解决 访问 https://www.jianshu.com/p/83dece153a22

**Comment by yunShare** [comment]
添加QQ 1172345589
