### ISSUE TITLE
还原wxml文件时的报错

### ISSUE THREAD

**Issue by marty0929** [qwerty472123/wxappUnpacker#45]
```
C:\Users\Administrator\Desktop\wxappUnpacker-master>node wuWxapkg.js list/douban2.wxapkg
Unpack file list/douban2.wxapkg...

Header info:
  firstMark: 0xbe
  unknownInfo:  0
  infoListLength:  984
  dataLength:  178842
  lastMark: 0xed

File list info:
  fileCount:  26
{ name: '/assets/tabbar/me_selected.png', off: 998, size: 1075 }
{ name: '/assets/tabbar/me.png', off: 2073, size: 1456 }
{ name: '/assets/tabbar/movie_selected.png',
  off: 3529,
  size: 1309 }
{ name: '/assets/tabbar/movie.png', off: 4838, size: 1371 }
{ name: '/app-config.json', off: 6209, size: 8305 }
{ name: '/app-service.js', off: 14514, size: 73415 }
{ name: '/common/templates/comment.html', off: 87929, size: 273 }
{ name: '/common/templates/movie.html', off: 88202, size: 271 }
{ name: '/common/templates/review.html', off: 88473, size: 272 }
{ name: '/common/templates/score.html', off: 88745, size: 271 }
{ name: '/common/templates/search-bar.html',
  off: 89016,
  size: 276 }
{ name: '/common/templates/short-comment.html',
  off: 89292,
  size: 279 }
{ name: '/pages/index/index.html', off: 89571, size: 299 }
{ name: '/pages/review/detail.html', off: 89870, size: 2079 }
{ name: '/pages/review/list.html', off: 91949, size: 337 }
{ name: '/pages/search/search.html', off: 92286, size: 922 }
{ name: '/pages/short-comment/list.html', off: 93208, size: 711 }
{ name: '/pages/subject/mark.html', off: 93919, size: 825 }
{ name: '/pages/subject/movie-list.html', off: 94744, size: 613 }
{ name: '/pages/subject/movie.html', off: 95357, size: 3741 }
{ name: '/pages/user/bind-phone.html', off: 99098, size: 327 }
{ name: '/pages/user/login.html', off: 99425, size: 867 }
{ name: '/pages/user/me.html', off: 100292, size: 432 }
{ name: '/pages/user/password-login.html',
  off: 100724,
  size: 295 }
{ name: '/pages/user/userinfo.html', off: 101019, size: 288 }
{ name: '/page-frame.html', off: 101307, size: 78533 }
Saving files...
Unpack done.
Split app-service.js and make up configs & wxss & wxml & wxs...

C:\Users\Administrator\Desktop\wxappUnpacker-master\node_modules\vm2\lib\main.js:218
                        throw this._internal.Decontextify.value(e);
                        ^
SyntaxError: Illegal return statement
    at VMScript.compile (C:\Users\Administrator\Desktop\wxappUnpacker-master\node_modules\vm2\lib\main.js:78:20)
    at VM.run (C:\Users\Administrator\Desktop\wxappUnpacker-master\node_modules\vm2\lib\main.js:212:52)
    at z (C:\Users\Administrator\Desktop\wxappUnpacker-master\wuWxml.js:294:7)
    at z (C:\Users\Administrator\Desktop\wxappUnpacker-master\wuRestoreZ.js:206:17)
    at catchZ (C:\Users\Administrator\Desktop\wxappUnpacker-master\wuRestoreZ.js:12:2)
    at getZ (C:\Users\Administrator\Desktop\wxappUnpacker-master\wuRestoreZ.js:206:2)
    at wu.get.code (C:\Users\Administrator\Desktop\wxappUnpacker-master\wuWxml.js:282:3)
    at ioLimit.runWithCb (C:\Users\Administrator\Desktop\wxappUnpacker-master\wuLib.js:80:8)
    at agent (C:\Users\Administrator\Desktop\wxappUnpacker-master\wuLib.js:54:14)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
```

解析page-frame.html时报错，尝试过解压之后分部解析还原，依然报错。

**Comment by marty0929** [comment]
[douban2.wxapkg.zip](https://github.com/qwerty472123/wxappUnpacker/files/1982004/douban2.wxapkg.zip)

**Comment by marty0929** [comment]
@qwerty472123  这个小程序是豆瓣评分，使用过之后，缓存文件会生成两个wxapkg文件，下面的是另外一个，解压之后是很多jswen文件和两个html文件，不知报错是不是和这个有关系。
[douban1.wxapkg.zip](https://github.com/qwerty472123/wxappUnpacker/files/1982102/douban1.wxapkg.zip)

**Comment by qwerty472123** [comment]
这个小程序版本是`v0.6vv_20170214_fbi`太低了 低版本这个解包器是不会支持的
另外一个包里面应该是一些用来适配这个低版本的文件（高版本微信会自带的，低版本的需要下载）

**Comment by marty0929** [comment]
@MomoPush 是和微信版本有关系吗？还是和小程序源文件有关系？

**Comment by qwerty472123** [comment]
过低的微信版本会为了正常运行高版本小程序提供支持包
然后似乎不能提供最新的…
具体不了解
