### ISSUE TITLE
Cannot find module 'uglify-es'   why always prompt

### ISSUE THREAD

**Issue by yufan2014** [qwerty472123/wxappUnpacker#49]
(如果你是要反馈 bug, 请按以下格式书写 Issue; 如果你遇到的是 Node.js 使用问题, 请尽可能依赖搜索引擎解决问题; 任何对某类小程序包的适配问题都应提供 wxapkg 程序包，否则直接 Close 处理; 提交前请确认 wxapkg 程序包版本不小于 v0.6vv_20180111_fbi (直接用文本编辑器打开 wxapkg包搜索 v0.6vv 即可查到), 旧版本不提供支持, 相关 Issue 直接 Close 处理。)

程序执行命令(可选):

程序执行错误信息(如果反馈是抛出异常的错误，必填):

```
Error: Cannot find module 'uglify-es'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/handongyu/Desktop/wxappUnpacker-0.2.2/wuJs.js:3:16)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
```

程序结果错误信息(如果反馈不是抛出异常的错误, 必填, 请尽可能详细描述):

程序包(你所要解压的程序包地址, 可为网盘链接, 也可直接上传[上传前请先打包]. 必填):

其他附加内容:

**Comment by qwerty472123** [comment]
请安装好 uglify-es包后再操作
具体安装方法见readme和百度

**Comment by zhangnew** [comment]
如果在 `npm install` 的时候加了 -g 参数，还报错找不到模块，执行 `npm link uglify-es` 就可以了，不需要重新 `install`
