### ISSUE TITLE
还原wxss错误，如下图，求解

### ISSUE THREAD

**Issue by gococ** [qwerty472123/wxappUnpacker#5]
```
> D:\Program Files\nodejs\node_modules\npm\node_modules\vm2\lib\main.js:218
                        throw this._internal.Decontextify.value(e);
                        ^
ReferenceError: __wxAppCode__ is not defined
    at vm.js:2:6
    at ContextifyScript.Script.runInContext (vm.js:59:29)
    at VM.run (D:\Program Files\nodejs\node_modules\npm\node_modules\vm2\lib\mai
n.js:212:72)
    at runVM (C:\Users\wanji\Desktop\wxappUnpacker-master\wuWxss.js:47:5)
    at runOnce (C:\Users\wanji\Desktop\wxappUnpacker-master\wuWxss.js:61:26)
    at Array.preRun (C:\Users\wanji\Desktop\wxappUnpacker-master\wuWxss.js:1
00:5)
    at CntEvent.decount (C:\Users\wanji\Desktop\wxappUnpacker-master\wuLib.j
s:17:43)
    at fs.writeFile.err (C:\Users\wanji\Desktop\wxappUnpacker-master\wuLib.j
s:37:11)
    at FSReqWrap.oncomplete (fs.js:135:15)
```

总是在出现这个错误提示，求解 #

**Comment by qwerty472123** [comment]
@gococ 可以看看你要还原的 wxapkg 包吗。
只是忽视错误的话，将runVM第一行改为试试
	let vm=new VM({sandbox:{wxAppCode(){},setCssToHead:cssRebuild.bind({cssFile:name})}});
不过具体 wxAppCode 在干什么，需要分析。

**Comment by gococ** [comment]
改了代码也不行，你看看包在下面
[wx.zip](https://github.com/qwerty472123/wxappUnpacker/files/1832160/wx.zip)

**Comment by marty0929** [comment]
我这边直接运wuWxapkg.js最后也是出现楼上的这个问题，而且在解压（是解压完，并没有执行编译app-config.json等文件之前）完成之后会报以下错误：

```
{ name: '/pages/transferPaySuccess/transferPaySuccess.html',
  off: 1204158,
  size: 589 }
{ name: '/pages/verificationCodePage/verificationCodePage.html',
  off: 1204747,
  size: 1686 }
{ name: '/page-frame.html', off: 1206433, size: 1232954 }
Saving files...
Unpack done.
Split app-service.js and make up configs & wxss & wxml & wxs...
Decompile ./components/backToHomePage/backToHomePage.wxml...
error on ./components/backToHomePage/backToHomePage.wxml
err:  Error: Unknown type of object in _m attrs array:
    at analyze (C:\Users\Administrator\Desktop\抓包资料\wxappUnpacker-master\wuWxml.js:97:22)
    at doWxml (C:\Users\Administrator\Desktop\抓包资料\wxappUnpacker-master\wuWxml.js:246:2)
    at tryWxml (C:\Users\Administrator\Desktop\抓包资料\wxappUnpacker-master\wuWxml.js:265:3)
    at wu.get.code (C:\Users\Administrator\Desktop\抓包资料\wxappUnpacker-master\wuWxml.js:307:23)
    at fs.readFile (C:\Users\Administrator\Desktop\抓包资料\wxappUnpacker-master\wuLib.js:44:8)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
Decompile ./components/pageQRCode/pageQRCode.wxml...
Decompile success!
Decompile ./components/wxParse/wxParse.wxml...
Decompile success!
```

**Comment by qwerty472123** [comment]
解包结果如下
[_wx.zip](https://github.com/qwerty472123/wxappUnpacker/files/1833326/_wx.zip)
应该是正常了。
同时程序也已经更新

**Comment by 0513Cassie** [comment]
err:  Error: Empty str in prop
    at Error (native)
    at wxmlify (C:\Users\win7\wuWxml.js:179:47)
    at elemToString (C:\Users\win7\wuWxml.js:233:57)
    at doWxml (C:\Users\win7\wuWxml.js:250:33)
    at tryWxml (C:\Users\win7\wuWxml.js:267:3)
    at z (C:\Users\win7\wuWxml.js:311:23)
    at z (C:\Users\win7\wuRestoreZ.js:216:17)
    at catchZ (C:\Users\win7\wuRestoreZ.js:12:2)
    at getZ (C:\Users\win7\wuRestoreZ.js:216:2)
    at wu.get.code (C:\Users\win7\wuWxml.js:282:3)
Decompile ./pages/convert/index.wxml...

**Comment by 0513Cassie** [comment]
您好 可以请教下这个问题吗
