### ISSUE TITLE
你好，问下解包中js 跟json都可以，wxml解析失败

### ISSUE THREAD

**Issue by dengbaoling** [qwerty472123/wxappUnpacker#51]
程序执行命令(可选):

程序执行错误信息(如果反馈是抛出异常的错误，必填):

```C:\Users\Dell\Desktop\小程序源码\腾讯视频>node wuWxml.js [-m]  page-frame.html
C:\Users\Dell\Desktop\小程序源码\腾讯视频\wuLib.js:79
                if(err)throw Error("Read file error: "+err);
                       ^

Error: Read file error: Error: ENOENT: no such file or directory, open 'C:\Users\Dell\Desktop\小程序源码\腾讯视频\[-m]'
    at ReadFileContext.ioLimit.runWithCb (C:\Users\Dell\Desktop\小程序源码\腾讯视频\wuLib.js:79:16)
    at ReadFileContext.agent [as callback] (C:\Users\Dell\Desktop\小程序源码\腾讯视频\wuLib.js:54:14)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:359:13)

C:\Users\Dell\Desktop\小程序源码\腾讯视频>
复制到这里


```

程序结果错误信息(如果反馈不是抛出异常的错误, 必填, 请尽可能详细描述):

程序包(你所要解压的程序包地址, 可为网盘链接, 也可直接上传[上传前请先打包]. 必填):

其他附加内容:
![6](https://user-images.githubusercontent.com/17171011/40266266-7a73c690-5b7a-11e8-89a2-d71eb348fe92.png)

[1267910674_36.zip](https://github.com/qwerty472123/wxappUnpacker/files/2019241/1267910674_36.zip)

**Comment by qwerty472123** [comment]
[-m]表示-m是可选参数啊
你直接
node wuWxml.js 文件名
好了

**Comment by dengbaoling** [comment]
好的
