### ISSUE TITLE
解析报错

### ISSUE THREAD

**Issue by JeffreyWxj** [qwerty472123/wxappUnpacker#52]
node wuWxapkg.js ./pkgs/xxx.wxapkg

```
error on ./pages/logs/logs.wxml
err:  Error: Empty str in prop
    at wxmlify (E:\Jeffrey\Desktop\wxappUnpacker\wuWxml.js:179:47)
    at elemToString (E:\Jeffrey\Desktop\wxappUnpacker\wuWxml.js:233:57)
    at doWxml (E:\Jeffrey\Desktop\wxappUnpacker\wuWxml.js:250:33)
    at tryWxml (E:\Jeffrey\Desktop\wxappUnpacker\wuWxml.js:267:3)
    at z (E:\Jeffrey\Desktop\wxappUnpacker\wuWxml.js:311:23)
    at z (E:\Jeffrey\Desktop\wxappUnpacker\wuRestoreZ.js:206:17)
    at catchZ (E:\Jeffrey\Desktop\wxappUnpacker\wuRestoreZ.js:12:2)
    at getZ (E:\Jeffrey\Desktop\wxappUnpacker\wuRestoreZ.js:206:2)
    at wu.get.code (E:\Jeffrey\Desktop\wxappUnpacker\wuWxml.js:282:3)
    at ioLimit.runWithCb (E:\Jeffrey\Desktop\wxappUnpacker\wuLib.js:80:8)

```
[xxx.zip](https://github.com/qwerty472123/wxappUnpacker/files/2019463/xxx.zip)

**Comment by qwerty472123** [comment]
版本`v0.6vv_20180104_fbi`老于最低支持版本`v0.6vv_20180111_fbi`
不修复
