### ISSUE TITLE
Magic number is not correct!

### ISSUE THREAD

**Issue by qingnichitudou** [qwerty472123/wxappUnpacker#588]
if (firstMark != 0xbe || lastMark != 0xed) throw Error("Magic number is not correct!");
                                             ^

Error: Magic number is not correct!
    at header (E:\天阳宏盛\小程序反编译项目\wxappUnpacker-master\wuWxapkg.js:20:52)
    at wu.get.buf (E:\天阳宏盛\小程序反编译项目\wxappUnpacker-master\wuWxapkg.js:111:40)
    at ioLimit.runWithCb (E:\天阳宏盛\小程序反编译项目\wxappUnpacker-master\wuLib.js:80:8)
    at agent (E:\天阳宏盛\小程序反编译项目\wxappUnpacker-master\wuLib.js:54:14)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)

**Comment by qwerty472123** [comment]
非本项目考虑的wxapkg格式文件
