### ISSUE TITLE
能否提供详细一点的使用文档呢？

### ISSUE THREAD

**Issue by marty0929** [qwerty472123/wxappUnpacker#6]
首先感谢技术分享，遇到一下问题，希望能得到解答：

这些依赖包根据,md中所属，都下载完毕，然后这些需要怎么关联？我这边一直提示以下问题：

```
C:\Users\Administrator\Desktop\抓包资料\wxappUnpacker-master>node wuConfig.js C:\Users\Administrator\Desktop\wxapkg2\app-config.json
C:\Users\Administrator\Desktop\抓包资料\wxappUnpacker-master\wuConfig.js:18
                                for(let e of app.tabBar.list){
                                                        ^

TypeError: Cannot read property 'list' of undefined
    at Array.digestsEvent.add (C:\Users\Administrator\Desktop\抓包资料\wxappUnpacker-master\wuConfig.js:18:29)
    at CntEvent.decount (C:\Users\Administrator\Desktop\抓包资料\wxappUnpacker-master\wuLib.js:17:43)
    at wu.get.data (C:\Users\Administrator\Desktop\抓包资料\wxappUnpacker-master\wuConfig.js:40:19)
    at fs.readFile (C:\Users\Administrator\Desktop\抓包资料\wxappUnpacker-master\wuLib.js:44:8)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
```

**Comment by qwerty472123** [comment]
一般直接调用`node wuWxapkg.js <Wxapkg 包的路径>`即可。
不过这问题似乎是`app-config.json`和本程序能识别的区别较大所致。
可以发一下你的Wxapkg 包 或app-config.json文件吗?

**Comment by qwerty472123** [comment]
看了一下你的另一个发帖，说明你的Wxapkg和本程序匹配的版本差别较大了，请发送Wxapkg 包，不然我也没法凭空分析╮(╯▽╰)╭

**Comment by bmy5585** [comment]
有同样的需求，可不可以出一个使用流程的文档？

**Comment by marty0929** [comment]
下面的是原包：
[_-49151769_1.zip](https://github.com/qwerty472123/wxappUnpacker/files/1835695/_-49151769_1.zip)

这个是app-config.json文件：
[app-config.zip](https://github.com/qwerty472123/wxappUnpacker/files/1835716/app-config.zip)

**Comment by marty0929** [comment]
通过解压，在./components\backToHomePage目录下，会有一个backToHomePage.wxml.ori.js。并没有解析成wxml文件。

**Comment by qwerty472123** [comment]
看来一下啊，我这边执行`wuConfig`并没有报错。
然后`wxml`的解析是我有一个小bug，已修复~
