### ISSUE TITLE
wxss无法还原：TypeError: csstree.generate is not a function

### ISSUE THREAD

**Issue by hu-qi** [qwerty472123/wxappUnpacker#60]
- wxapkg 程序包版本：v0.6vv_20180125_fbi
- 程序执行命令:node .\wuWxapkg.js E:/test/_-2060217398_12.wxapkg
- 程序执行错误信息(如果反馈是抛出异常的错误，必填):
```
Guess wxss(first turn)...
Import count info: {}
Guess wxss(first turn) done.
Generate wxss(second turn)...
Generate wxss(second turn) done.
Save wxss...
E:\test\wxappUnpacker\wuWxss.js:140
                return cssbeautify(csstree.generate(ast),{indent:'    ',autosemicolon:true});
                                           ^

TypeError: csstree.generate is not a function
    at transformCss (E:\test\wxappUnpacker\wuWxss.js:140:30)
    at Array.preRun (E:\test\wxappUnpacker\wuWxss.js:181:63)
    at CntEvent.decount (E:\test\wxappUnpacker\wuLib.js:17:43)
    at ioLimit.runWithCb.err (E:\test\wxappUnpacker\wuLib.js:73:11)
    at agent (E:\test\wxappUnpacker\wuLib.js:54:14)
    at FSReqWrap.oncomplete (fs.js:135:15)
```
- 程序结果错误信息：
wxss被解析成了html，不过应该可以手动修改
![tim 20180601104603](https://user-images.githubusercontent.com/17986122/40818335-412476fa-6589-11e8-99fa-92e8b89f0762.png)

- 程序包:
[_-2060217398_12.wxapkg.zip](https://github.com/qwerty472123/wxappUnpacker/files/2060806/_-2060217398_12.wxapkg.zip)

**Comment by qwerty472123** [comment]
尝试用 npm install 来安装、更新一下 css-tree 吧
这属于依赖包配置的问题 与本项目本身无关...
