### ISSUE TITLE
ReferenceError: x is not defined

### ISSUE THREAD

**Issue by libp** [qwerty472123/wxappUnpacker#62]
(如果你是要反馈 bug, 请按以下格式书写 Issue; 如果你遇到的是 Node.js 使用问题, 请尽可能依赖搜索引擎解决问题; 任何对某类小程序包的适配问题都应提供 wxapkg 程序包，否则直接 Close 处理; 提交前请确认 wxapkg 程序包版本不小于 v0.6vv_20180111_fbi (直接用文本编辑器打开 wxapkg包搜索 v0.6vv 即可查到), 旧版本不提供支持, 相关 Issue 直接 Close 处理。)

程序执行命令(可选):

程序执行错误信息(如果反馈是抛出异常的错误，必填):

```
复制到这里
```

程序结果错误信息(如果反馈不是抛出异常的错误, 必填, 请尽可能详细描述):
File list info:
  fileCount:  6
{ name: '/app-config.json', off: 204, size: 646 }
{ name: '/app-service.js', off: 850, size: 5286 }
{ name: '/pages/about/about.html', off: 6136, size: 381 }
{ name: '/pages/index/index.html', off: 6517, size: 1150 }
{ name: '/pages/logs/logs.html', off: 7667, size: 386 }
{ name: '/page-frame.html', off: 8053, size: 103801 }
Saving files...
Unpack done.
Split app-service.js and make up configs & wxss & wxml & wxs...
Splitting "C:\Users\ruonan\Downloads\wxappUnpacker-master\wx\_-1937897314_1\app-service.js" done.

C:\Users\ruonan\Downloads\wxappUnpacker-master\node_modules\_vm2@3.6.0@vm2\lib\main.js:218
                        throw this._internal.Decontextify.value(e);
                        ^
ReferenceError: x is not defined
    at vm.js:162:10
    at ContextifyScript.Script.runInContext (vm.js:59:29)
    at VM.run (C:\Users\ruonan\Downloads\wxappUnpacker-master\node_modules\_vm2@3.6.0@vm2\lib\main.js:212:72)
    at z (C:\Users\ruonan\Downloads\wxappUnpacker-master\wuWxml.js:294:7)
    at z (C:\Users\ruonan\Downloads\wxappUnpacker-master\wuRestoreZ.js:206:17)
    at catchZ (C:\Users\ruonan\Downloads\wxappUnpacker-master\wuRestoreZ.js:12:2)
    at getZ (C:\Users\ruonan\Downloads\wxappUnpacker-master\wuRestoreZ.js:206:2)
    at wu.get.code (C:\Users\ruonan\Downloads\wxappUnpacker-master\wuWxml.js:282:3)
    at ioLimit.runWithCb (C:\Users\ruonan\Downloads\wxappUnpacker-master\wuLib.js:80:8)
    at agent (C:\Users\ruonan\Downloads\wxappUnpacker-master\wuLib.js:54:14)
程序包(你所要解压的程序包地址, 可为网盘链接, 也可直接上传[上传前请先打包]. 必填):

其他附加内容:

**Comment by qwerty472123** [comment]
请检查 wxapkg 程序包版本不小于 v0.6vv_20180111_fbi
另外就算是高版本 没样例怎么玩,..
