### ISSUE TITLE
反编译报错 Illegal return statement

### ISSUE THREAD

**Issue by zuoye520** [qwerty472123/wxappUnpacker#68]
程序反编译异常

```
E:\git_212\wxappUnpacker\node_modules\vm2\lib\main.js:218
                        throw this._internal.Decontextify.value(e);
                        ^
SyntaxError: Illegal return statement
    at VMScript.compile (E:\git_212\wxappUnpacker\node_modules\vm2\lib\main.js:78:20)
    at VM.run (E:\git_212\wxappUnpacker\node_modules\vm2\lib\main.js:212:52)
    at z (E:\git_212\wxappUnpacker\wuWxml.js:294:7)
    at z (E:\git_212\wxappUnpacker\wuRestoreZ.js:216:17)
    at catchZ (E:\git_212\wxappUnpacker\wuRestoreZ.js:12:2)
    at getZ (E:\git_212\wxappUnpacker\wuRestoreZ.js:216:2)
    at wu.get.code (E:\git_212\wxappUnpacker\wuWxml.js:282:3)
    at ioLimit.runWithCb (E:\git_212\wxappUnpacker\wuLib.js:80:8)
    at agent (E:\git_212\wxappUnpacker\wuLib.js:54:14)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
```

**Comment by qwerty472123** [comment]
应该是小程序版本过低 不支持
