### ISSUE TITLE
解包出错：SyntaxError: Unexpected token } 

### ISSUE THREAD

**Issue by xenv** [qwerty472123/wxappUnpacker#73]
程序执行命令(可选): node wuWxapkg.js 42.wxapkg

程序执行错误信息(如果反馈是抛出异常的错误，必填):

```
Unpack done.
Split app-service.js and make up configs & wxss & wxml & wxs...

D:\unpack\wxappUnpacker-master\node_modules\vm2\lib\main.js:218
                        throw this._internal.Decontextify.value(e);
                        ^
SyntaxError: Unexpected token }
    at VMScript.compile (D:\unpack\wxappUnpacker-master\node_modules\vm2\lib\main.js:78:20)
    at VM.run (D:\unpack\wxappUnpacker-master\node_modules\vm2\lib\main.js:212:52)
    at wu.get.code (D:\unpack\wxappUnpacker-master\wuJs.js:27:6)
    at ioLimit.runWithCb (D:\unpack\wxappUnpacker-master\wuLib.js:80:8)
    at agent (D:\unpack\wxappUnpacker-master\wuLib.js:54:14)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
```

程序包(你所要解压的程序包地址, 可为网盘链接, 也可直接上传[上传前请先打包]. 必填):
链接: https://pan.baidu.com/s/13JThTeU8Oyqx1kA3mqkQGg 密码: zpe9

谢谢

**Comment by Rowingamemaker** [comment]
我也是  可能微信改版了

**Comment by qwerty472123** [comment]
本项目目前暂不支持[插件](https://developers.weixin.qq.com/miniprogram/dev/framework/plugin/)
后续版本将会提供插件支持

**Comment by jackzhangsir** [comment]
@qwerty472123 你好大神，目前的版本能解析包含插件的apkg包吗？马上8月份了哦

**Comment by HuiNingTech** [comment]
期待插件

**Comment by echoyl** [comment]
读取插件还有救么？
小程序使用了插件wuJs解析就报错
如果将 app-service.js中的插件代码去除的话 是可以成功解析的
将 app-service.js中的 definePlugin("plugin://wxa75efa648b60994b", ...至 requirePlugin("plugin://wxa75efa648b60994b"); 这段代码清除，然后 
执行 node wuJs.js app-service.js  命令即不会报错成功解析了
期待更新

**Comment by HuiNingTech** [comment]
> 读取插件还有救么？
> 小程序使用了插件wuJs解析就报错
> 如果将 app-service.js中的插件代码去除的话 是可以成功解析的
> 将 app-service.js中的 definePlugin("plugin://wxa75efa648b60994b", ...至 requirePlugin("plugin://wxa75efa648b60994b"); 这段代码清除，然后
> 执行 node wuJs.js app-service.js 命令即不会报错成功解析了
> 期待更新

大佬，这个怎么弄的。为什么我的还是报错

**Comment by HuiNingTech** [comment]
> 读取插件还有救么？
> 小程序使用了插件wuJs解析就报错
> 如果将 app-service.js中的插件代码去除的话 是可以成功解析的
> 将 app-service.js中的 definePlugin("plugin://wxa75efa648b60994b", ...至 requirePlugin("plugin://wxa75efa648b60994b"); 这段代码清除，然后
> 执行 node wuJs.js app-service.js 命令即不会报错成功解析了
> 期待更新

大佬，这样成功，后面怎么能把所有源码解析完成呢

**Comment by echoyl** [comment]
> > 读取插件还有救么？
> > 小程序使用了插件wuJs解析就报错
> > 如果将 app-service.js中的插件代码去除的话 是可以成功解析的
> > 将 app-service.js中的 definePlugin("plugin://wxa75efa648b60994b", ...至 requirePlugin("plugin://wxa75efa648b60994b"); 这段代码清除，然后
> > 执行 node wuJs.js app-service.js 命令即不会报错成功解析了
> > 期待更新
> 
> 大佬，这样成功，后面怎么能把所有源码解析完成呢
wuWxapkg.js 这个是整体解包的，如果没有问题的话 使用这个命令就能把包解完，碰到比如这个插件还有分包之类的，就没办法解完了。
但是基本上已经把包解的差不多了，然后再手动解每个部分就行了
1.app-config.json 2.app-service.js 3.page-frame.html 分别用作者大神的1.wuConfig.js 2.wuJs.js 3.wuWxml.js 4.wuWxss.js 4个工具解析就能完成解析。
还有就是如果是插件的话 将app-service.js 与 page-frame.html 这两个里面的关于插件的部分去掉然后手动解析就可以了。插件的话估计得再手动解析。
分包的话我也是一个小包一个小包解的，暂时没法自动解析

**Comment by wzfxue** [comment]
> > > 读取插件还有救么？
> > > 小程序使用了插件wuJs解析就报错
> > > 如果将 app-service.js中的插件代码去除的话 是可以成功解析的
> > > 将 app-service.js中的 definePlugin("plugin://wxa75efa648b60994b", ...至 requirePlugin("plugin://wxa75efa648b60994b"); 这段代码清除，然后
> > > 执行 node wuJs.js app-service.js 命令即不会报错成功解析了
> > > 期待更新
> > 
> > 
> > 大佬，这样成功，后面怎么能把所有源码解析完成呢
> 
> wuWxapkg.js 这个是整体解包的，如果没有问题的话 使用这个命令就能把包解完，碰到比如这个插件还有分包之类的，就没办法解完了。
> 但是基本上已经把包解的差不多了，然后再手动解每个部分就行了
> 1.app-config.json 2.app-service.js 3.page-frame.html 分别用作者大神的1.wuConfig.js 2.wuJs.js 3.wuWxml.js 4.wuWxss.js 4个工具解析就能完成解析。
> 还有就是如果是插件的话 将app-service.js 与 page-frame.html 这两个里面的关于插件的部分去掉然后手动解析就可以了。插件的话估计得再手动解析。
> 分包的话我也是一个小包一个小包解的，暂时没法自动解析

F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-master>node .\wuWxss.js F:\JAVA
_WORK\USER_WORK\weixin_work\kaoqingtong\_-13438613_4\page-frame.html
F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-master\wuLib.js:96
                        if(err)throw Error("Scan dir error: "+err);
                               ^

Error: Scan dir error: Error: ENOTDIR: not a directory, scandir 'F:\JAVA_WORK\US
ER_WORK\weixin_work\kaoqingtong\_-13438613_4\page-frame.html'
    at Error (native)
    at ioLimit.runWithCb (F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-maste
r\wuLib.js:96:17)
    at agent (F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-master\wuLib.js:5
4:14)
    at FSReqWrap.oncomplete (fs.js:123:15)

F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-master>node .\wuWxml.js F:\JAVA
_WORK\USER_WORK\weixin_work\kaoqingtong\_-13438613_4\page-frame.html

F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-master\node_modules\vm2\lib\mai
n.js:210
                        throw this._internal.Decontextify.value(e);
                        ^
SyntaxError: Illegal return statement
    at VMScript.compile (F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-master
\node_modules\vm2\lib\main.js:78:20)
    at VM.run (F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-master\node_modu
les\vm2\lib\main.js:204:52)
    at z (F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-master\wuWxml.js:366:
7)
    at z (F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-master\wuRestoreZ.js:
244:17)
    at catchZ (F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-master\wuRestore
Z.js:28:2)
    at getZ (F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-master\wuRestoreZ.
js:244:2)
    at wu.get.code (F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-master\wuWx
ml.js:354:3)
    at ioLimit.runWithCb (F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-maste
r\wuLib.js:80:8)
    at agent (F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-master\wuLib.js:5
4:14)
    at tryToString (fs.js:457:3)

F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-master>node .\wuWxml.js F:\JAVA
_WORK\USER_WORK\weixin_work\kaoqingtong\_-13438613_4\page-frame.html

F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-master\node_modules\vm2\lib\mai
n.js:210
                        throw this._internal.Decontextify.value(e);
                        ^
SyntaxError: Illegal return statement
    at VMScript.compile (F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-master
\node_modules\vm2\lib\main.js:78:20)
    at VM.run (F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-master\node_modu
les\vm2\lib\main.js:204:52)
    at z (F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-master\wuWxml.js:366:
7)
    at z (F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-master\wuRestoreZ.js:
244:17)
    at catchZ (F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-master\wuRestore
Z.js:28:2)
    at getZ (F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-master\wuRestoreZ.
js:244:2)
    at wu.get.code (F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-master\wuWx
ml.js:354:3)
    at ioLimit.runWithCb (F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-maste
r\wuLib.js:80:8)
    at agent (F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-master\wuLib.js:5
4:14)
    at tryToString (fs.js:457:3)

F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-master>node .\wuXss.js F:\JAVA_
WORK\USER_WORK\weixin_work\kaoqingtong\_-13438613_4\
module.js:471
    throw err;
    ^

Error: Cannot find module 'F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-mast
er\wuXss.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:502:3

F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-master>node .\wuXss.js F:\JAVA_
WORK\USER_WORK\weixin_work\kaoqingtong\_-13438613_4\page-frame.html
module.js:471
    throw err;
    ^

Error: Cannot find module 'F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-mast
er\wuXss.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:502:3

F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-master>node .\wuXss.js F:\JAVA_
WORK\USER_WORK\weixin_work\kaoqingtong\_-13438613_4\page-frame.html
module.js:471
    throw err;
    ^

Error: Cannot find module 'F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-mast
er\wuXss.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:502:3

F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-master>node .\wuWXss.js F:\JAVA
_WORK\USER_WORK\weixin_work\kaoqingtong\_-13438613_4\page-frame.html
F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-master\wuLib.js:96
                        if(err)throw Error("Scan dir error: "+err);
                               ^

Error: Scan dir error: Error: ENOTDIR: not a directory, scandir 'F:\JAVA_WORK\US
ER_WORK\weixin_work\kaoqingtong\_-13438613_4\page-frame.html'
    at Error (native)
    at ioLimit.runWithCb (F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-maste
r\wuLib.js:96:17)
    at agent (F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-master\wuLib.js:5
4:14)
    at FSReqWrap.oncomplete (fs.js:123:15)

我这里一直报错，请问有什么办法吗？小程序中没有插件

**Comment by lyz419061050** [comment]
插件功能还没有支持是吗？

**Comment by lyz419061050** [comment]
> 
> 
> 插件功能还没有支持是吗？

我已经把里面所有的 plugin 都删除掉了，在解 page-frame.js 的时候提示  now is not defined.

d:\small\wu\node_modules\vm2\lib\main.js:210
                        throw this._internal.Decontextify.value(e);
                        ^
ReferenceError: now is not defined
    at vm.js:1:1
    at Script.runInContext (vm.js:133:20)
    at VM.run (d:\small\wu\node_modules\vm2\lib\main.js:204:72)
    at z (d:\small\wu\wuwxml.js:366:7)
    at z (d:\small\wu\wuRestoreZ.js:244:17)
    at catchZ (d:\small\wu\wuRestoreZ.js:28:2)
    at getZ (d:\small\wu\wuRestoreZ.js:244:2)
    at wu.get.code (d:\small\wu\wuwxml.js:354:3)
    at ioLimit.runWithCb (d:\small\wu\wuLib.js:80:8)
    at agent (d:\small\wu\wuLib.js:54:14)

**Comment by NullYing** [comment]
> > > 读取插件还有救么？
> > > 小程序使用了插件wuJs解析就报错
> > > 如果将 app-service.js中的插件代码去除的话 是可以成功解析的
> > > 将 app-service.js中的 definePlugin("plugin://wxa75efa648b60994b", ...至 requirePlugin("plugin://wxa75efa648b60994b"); 这段代码清除，然后
> > > 执行 node wuJs.js app-service.js 命令即不会报错成功解析了
> > > 期待更新
> > 
> > 
> > 大佬，这样成功，后面怎么能把所有源码解析完成呢
> 
> wuWxapkg.js 这个是整体解包的，如果没有问题的话 使用这个命令就能把包解完，碰到比如这个插件还有分包之类的，就没办法解完了。
> 但是基本上已经把包解的差不多了，然后再手动解每个部分就行了
> 1.app-config.json 2.app-service.js 3.page-frame.html 分别用作者大神的1.wuConfig.js 2.wuJs.js 3.wuWxml.js 4.wuWxss.js 4个工具解析就能完成解析。
> 还有就是如果是插件的话 将app-service.js 与 page-frame.html 这两个里面的关于插件的部分去掉然后手动解析就可以了。插件的话估计得再手动解析。
> 分包的话我也是一个小包一个小包解的，暂时没法自动解析

js我已经解析成功了，不过wxml和wxss一直解不出来，请问如何根据这个错误debug
```

/Users/123/src/wxappUnpacker/node_modules/vm2/lib/main.js:210
			throw this._internal.Decontextify.value(e);
			^
vm.js:2
_C
^^

SyntaxError: Unexpected end of input
    at new Script (vm.js:83:7)
    at VMScript.compile (/Users/123/src/wxappUnpacker/node_modules/vm2/lib/main.js:78:20)
    at VM.run (/Users/123/src/wxappUnpacker/node_modules/vm2/lib/main.js:204:52)
    at wu.get.code (/Users/123/src/wxappUnpacker/wuWxss.js:160:16)
    at ioLimit.runWithCb (/Users/123/src/wxappUnpacker/wuLib.js:80:8)
    at agent (/Users/123/src/wxappUnpacker/wuLib.js:54:14)
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
```

**Comment by 15192095633** [comment]
> > > > 读取插件还有救么？
> > > > 小程序使用了插件wuJs解析就报错
> > > > 如果将 app-service.js中的插件代码去除的话 是可以成功解析的
> > > > 将 app-service.js中的 definePlugin("plugin://wxa75efa648b60994b", ...至 requirePlugin("plugin://wxa75efa648b60994b"); 这段代码清除，然后
> > > > 执行 node wuJs.js app-service.js 命令即不会报错成功解析了
> > > > 期待更新
> > > 
> > > 
> > > 大佬，这样成功，后面怎么能把所有源码解析完成呢
> > 
> > 
> > wuWxapkg.js 这个是整体解包的，如果没有问题的话 使用这个命令就能把包解完，碰到比如这个插件还有分包之类的，就没办法解完了。
> > 但是基本上已经把包解的差不多了，然后再手动解每个部分就行了
> > 1.app-config.json 2.app-service.js 3.page-frame.html 分别用作者大神的1.wuConfig.js 2.wuJs.js 3.wuWxml.js 4.wuWxss.js 4个工具解析就能完成解析。
> > 还有就是如果是插件的话 将app-service.js 与 page-frame.html 这两个里面的关于插件的部分去掉然后手动解析就可以了。插件的话估计得再手动解析。
> > 分包的话我也是一个小包一个小包解的，暂时没法自动解析
> 
> F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-master>node .\wuWxss.js F:\JAVA
> _WORK\USER_WORK\weixin_work\kaoqingtong_-13438613_4\page-frame.html
> F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-master\wuLib.js:96
> if(err)throw Error("Scan dir error: "+err);
> ^
> 
> Error: Scan dir error: Error: ENOTDIR: not a directory, scandir 'F:\JAVA_WORK\US
> ER_WORK\weixin_work\kaoqingtong_-13438613_4\page-frame.html'
> at Error (native)
> at ioLimit.runWithCb (F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-maste
> r\wuLib.js:96:17)
> at agent (F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-master\wuLib.js:5
> 4:14)
> at FSReqWrap.oncomplete (fs.js:123:15)
> 
> F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-master>node .\wuWxml.js F:\JAVA
> _WORK\USER_WORK\weixin_work\kaoqingtong_-13438613_4\page-frame.html
> 
> F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-master\node_modules\vm2\lib\mai
> n.js:210
> throw this._internal.Decontextify.value(e);
> ^
> SyntaxError: Illegal return statement
> at VMScript.compile (F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-master
> \node_modules\vm2\lib\main.js:78:20)
> at VM.run (F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-master\node_modu
> les\vm2\lib\main.js:204:52)
> at z (F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-master\wuWxml.js:366:
> 7)
> at z (F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-master\wuRestoreZ.js:
> 244:17)
> at catchZ (F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-master\wuRestore
> Z.js:28:2)
> at getZ (F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-master\wuRestoreZ.
> js:244:2)
> at wu.get.code (F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-master\wuWx
> ml.js:354:3)
> at ioLimit.runWithCb (F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-maste
> r\wuLib.js:80:8)
> at agent (F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-master\wuLib.js:5
> 4:14)
> at tryToString (fs.js:457:3)
> 
> F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-master>node .\wuWxml.js F:\JAVA
> _WORK\USER_WORK\weixin_work\kaoqingtong_-13438613_4\page-frame.html
> 
> F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-master\node_modules\vm2\lib\mai
> n.js:210
> throw this._internal.Decontextify.value(e);
> ^
> SyntaxError: Illegal return statement
> at VMScript.compile (F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-master
> \node_modules\vm2\lib\main.js:78:20)
> at VM.run (F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-master\node_modu
> les\vm2\lib\main.js:204:52)
> at z (F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-master\wuWxml.js:366:
> 7)
> at z (F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-master\wuRestoreZ.js:
> 244:17)
> at catchZ (F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-master\wuRestore
> Z.js:28:2)
> at getZ (F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-master\wuRestoreZ.
> js:244:2)
> at wu.get.code (F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-master\wuWx
> ml.js:354:3)
> at ioLimit.runWithCb (F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-maste
> r\wuLib.js:80:8)
> at agent (F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-master\wuLib.js:5
> 4:14)
> at tryToString (fs.js:457:3)
> 
> F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-master>node .\wuXss.js F:\JAVA_
> WORK\USER_WORK\weixin_work\kaoqingtong_-13438613_4
> module.js:471
> throw err;
> ^
> 
> Error: Cannot find module 'F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-mast
> er\wuXss.js'
> at Function.Module._resolveFilename (module.js:469:15)
> at Function.Module._load (module.js:417:25)
> at Module.runMain (module.js:604:10)
> at run (bootstrap_node.js:389:7)
> at startup (bootstrap_node.js:149:9)
> at bootstrap_node.js:502:3
> 
> F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-master>node .\wuXss.js F:\JAVA_
> WORK\USER_WORK\weixin_work\kaoqingtong_-13438613_4\page-frame.html
> module.js:471
> throw err;
> ^
> 
> Error: Cannot find module 'F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-mast
> er\wuXss.js'
> at Function.Module._resolveFilename (module.js:469:15)
> at Function.Module._load (module.js:417:25)
> at Module.runMain (module.js:604:10)
> at run (bootstrap_node.js:389:7)
> at startup (bootstrap_node.js:149:9)
> at bootstrap_node.js:502:3
> 
> F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-master>node .\wuXss.js F:\JAVA_
> WORK\USER_WORK\weixin_work\kaoqingtong_-13438613_4\page-frame.html
> module.js:471
> throw err;
> ^
> 
> Error: Cannot find module 'F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-mast
> er\wuXss.js'
> at Function.Module._resolveFilename (module.js:469:15)
> at Function.Module._load (module.js:417:25)
> at Module.runMain (module.js:604:10)
> at run (bootstrap_node.js:389:7)
> at startup (bootstrap_node.js:149:9)
> at bootstrap_node.js:502:3
> 
> F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-master>node .\wuWXss.js F:\JAVA
> _WORK\USER_WORK\weixin_work\kaoqingtong_-13438613_4\page-frame.html
> F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-master\wuLib.js:96
> if(err)throw Error("Scan dir error: "+err);
> ^
> 
> Error: Scan dir error: Error: ENOTDIR: not a directory, scandir 'F:\JAVA_WORK\US
> ER_WORK\weixin_work\kaoqingtong_-13438613_4\page-frame.html'
> at Error (native)
> at ioLimit.runWithCb (F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-maste
> r\wuLib.js:96:17)
> at agent (F:\JAVA_WORK\USER_WORK\weixin_work\wxappUnpacker-master\wuLib.js:5
> 4:14)
> at FSReqWrap.oncomplete (fs.js:123:15)
> 
> 我这里一直报错，请问有什么办法吗？小程序中没有插件
我按照你说的把 app-service.js 中的插件删除了，还是不行啊。跟以前一样的错误!

**Comment by 7423385** [comment]
QQ7423385 分包插件能解 成功后付费
