### ISSUE TITLE
程序执行粗粗哦

### ISSUE THREAD

**Issue by 420chen** [qwerty472123/wxappUnpacker#74]
我的 node 版本
$ node -v
v4.0.0

1、好几个文件都出错了
执行
node wuConfig.js  _11ddddd.wxapkg

提示出错
wuConfig.js:5
	let dir=path.dirname(configFile);
	^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3

2、node wuConfig.js  _11ddddd.wxapkg
wuConfig.js:5
	let dir=path.dirname(configFile);
	^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3

**Comment by qwerty472123** [comment]
node.js 版本太低了...
升级吧

**Comment by 420chen** [comment]
什么版本的node.js 才合适？

**Comment by qwerty472123** [comment]
我用的是Current（Latest）
LTS-Current间的node.js应该都没问题
