### ISSUE TITLE
先是路径不对，然后是 vm2 报错

### ISSUE THREAD

**Issue by dev-itsheng** [qwerty472123/wxappUnpacker#76]
(如果你是要反馈 bug, 请按以下格式书写 Issue; 如果你遇到的是 Node.js 使用问题, 请尽可能依赖搜索引擎解决问题; 任何对某类小程序包的适配问题都应提供 wxapkg 程序包，否则直接 Close 处理; 提交前请确认 wxapkg 程序包版本不小于 v0.6vv_20180111_fbi (直接用文本编辑器打开 wxapkg包搜索 v0.6vv 即可查到), 旧版本不提供支持, 相关 Issue 直接 Close 处理。)

程序执行命令(可选):

```
node wuWxapkg.js C:\Users\Mrwang\Desktop\t\4.wxapkg
```

程序执行错误信息(如果反馈是抛出异常的错误，必填):

首先是路径错误

```
Error: Save file error: Error: ENOENT: no such file or directory, open 'C:\Users\components\wxc-mask\index.json'
    at ioLimit.runWithCb.err (C:\Users\Mrwang\Desktop\wxappUnpacker-master\wuLib.js:74:16)
    at agent (C:\Users\Mrwang\Desktop\wxappUnpacker-master\wuLib.js:54:14)
    at fs.js:1287:7
    at FSReqWrap.oncomplete (fs.js:169:20)
```

按照报错信息的提示，我修改了源文件，加了一条路径转换，映射到正确的路径上

```javascript
// WuLib.js 第 72 行之前
name = name.replace('C:\\Users\\components\\', 'C:\\Users\\Mrwang\\Desktop\\t\\4\\components\\');
```

随后又报了另外一个错：

```
C:\Users\Mrwang\Desktop\wxappUnpacker-master\node_modules\vm2\lib\main.js:219
                        throw this._internal.Decontextify.value(e);
                        ^
vm.js:4
}
^

SyntaxError: Unexpected token }
    at new Script (vm.js:74:7)
    at VMScript.compile (C:\Users\Mrwang\Desktop\wxappUnpacker-master\node_modules\vm2\lib\main.js:79:20)
    at VM.run (C:\Users\Mrwang\Desktop\wxappUnpacker-master\node_modules\vm2\lib\main.js:213:52)
    at catchZ (C:\Users\Mrwang\Desktop\wxappUnpacker-master\wuRestoreZ.js:11:5)
    at getZ (C:\Users\Mrwang\Desktop\wxappUnpacker-master\wuRestoreZ.js:216:2)
    at wu.get.code (C:\Users\Mrwang\Desktop\wxappUnpacker-master\wuWxml.js:282:3)
    at ioLimit.runWithCb (C:\Users\Mrwang\Desktop\wxappUnpacker-master\wuLib.js:82:8)
    at agent (C:\Users\Mrwang\Desktop\wxappUnpacker-master\wuLib.js:54:14)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:440:3)
```

这个问题就无法解决了

程序结果错误信息(如果反馈不是抛出异常的错误, 必填, 请尽可能详细描述):

程序包(你所要解压的程序包地址, 可为网盘链接, 也可直接上传[上传前请先打包]. 必填):

[4.zip](https://github.com/qwerty472123/wxappUnpacker/files/2088645/4.zip)

其他附加内容:

**Comment by qwerty472123** [comment]
前一个问题没有遇到（可能是环境的问题？）
后一个是因为包中有插件 目前暂不支持 详见 #73
