### ISSUE TITLE
直接报错module.js:487

### ISSUE THREAD

**Issue by aa335418265** [qwerty472123/wxappUnpacker#79]
程序执行命令(可选):
```
node /Users/itx/wxappUnpacker/wuWxapkg.js f6de052da5316347d90f07ff05982386_1.wxapkg 
```

```
module.js:487
    throw err;
    ^

Error: Cannot find module 'js-beautify'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/itx/wxappUnpacker/wuJs.js:4:19)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

**Comment by wonderffee** [comment]
有执行npm install？

**Comment by qwerty472123** [comment]
见 #78 新版本需要重新执行 npm install
