### ISSUE TITLE
module.js:538 错误

### ISSUE THREAD

**Issue by bmy5585** [qwerty472123/wxappUnpacker#8]
安装了依赖包，执行 node wuWxapkg.js xx.wxapkg 提示以下错误：

module.js:538
    throw err;
    ^

Error: Cannot find module 'vm2'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (d:\wxappUnpacker\wuJs.js:4:12)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)

windows 10 下安装的 node.js 64位版本。

请问这是依赖包没有安装成功么？

**Comment by bmy5585** [comment]
npm install esprima -g
npm install css-tree -g
npm install cssbeautify -g
npm install vm2 -g
npm install uglify-es -g

这几个命令都执行过，运行的时候依然是会报错。windows 和 mac 都试过了，都是一样报错。

D:\wxappUnpacker>node wuWxml.js xx\page-frame.html
module.js:545
    throw err;
    ^

Error: Cannot find module 'vm2'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\wxappUnpacker\wuRestoreZ.js:2:12)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)

**Comment by qwerty472123** [comment]
网上去查一查 各种包require失败的方法吧… 情况多得很，但这应该与本项目就没什么关系了

**Comment by bmy5585** [comment]
第一次解决 node.js 很多傻瓜问题，见谅。百度，google我找相应的错误代码都没有找到原因。 我找台linux再试试。感谢。

**Comment by bmy5585** [comment]
windows 下 node 9.9.0

npm install esprima
npm install css-tree
npm install cssbeautify
npm install vm2
npm install uglify-es

重新执行一次就好了，去掉了 -g。

**Comment by qwerty472123** [comment]
-g是安装在全局
加了不行可能是node_path配置相关的问题
不加就安装在当前目录
安装在当前目录在一些情况的确更恰当
具体看你如何使用

**Comment by bmy5585** [comment]
path 我添加了，可能是添加有误。 我奇怪的是 mac 下也有这个问题。

去掉 -g 安装到当前目录能用，能用就好啦！
