### ISSUE TITLE
buffer.js:977     throw new RangeError('Index out of range');

### ISSUE THREAD

**Issue by cinoliu** [qwerty472123/wxappUnpacker#84]
$ node wuWxapkg.js  4.wxapkg 
Unpack file 4.wxapkg...

Header info:
buffer.js:977
    throw new RangeError('Index out of range');
    ^

RangeError: Index out of range
    at checkOffset (buffer.js:977:11)
    at Buffer.readUInt8 (buffer.js:1015:5)
    at header (/Downloads/wxappUnpacker-master/wuWxapkg.js:10:20)
    at wu.get.buf (/Downloads/wxappUnpacker-master/wuWxapkg.js:108:35)
    at ioLimit.runWithCb /Downloads/wxappUnpacker-master/wuLib.js:80:8)
    at agent (/Downloads/wxappUnpacker-master/wuLib.js:54:14)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)

**Comment by qwerty472123** [comment]
请按模板格式提交bug
你这样我只能知道 你的wxapkg 格式和正常的 wxapkg 格式不同
