### ISSUE TITLE
反编译 腾讯阅读  报错

### ISSUE THREAD

**Issue by Osub** [qwerty472123/wxappUnpacker#86]
```
Split app-service.js and make up configs & wxss & wxml & wxs...
Splitting "/Users/machero/Desktop/nextMarketing/wxapp/package/_241162262_2/app-service.js" done.

/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/node_modules/vm2/lib/main.js:218
                        throw this._internal.Decontextify.value(e);
                        ^
vm.js:32
return new x;
^^^^^^

SyntaxError: Illegal return statement
    at new Script (vm.js:51:7)
    at VMScript.compile (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/node_modules/vm2/lib/main.js:78:20)
    at VM.run (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/node_modules/vm2/lib/main.js:212:52)
    at z (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:294:7)
    at z (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuRestoreZ.js:216:17)
    at catchZ (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuRestoreZ.js:12:2)
    at getZ (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuRestoreZ.js:216:2)
    at wu.get.code (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:282:3)
    at ioLimit.runWithCb (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuLib.js:80:8)
    at agent (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuLib.js:54:14
```

**Comment by qwerty472123** [comment]
请阅读完issue_template并按要求发帖
