### ISSUE TITLE
反编译错误

### ISSUE THREAD

**Issue by Osub** [qwerty472123/wxappUnpacker#87]
```

Splitting "/Users/machero/Desktop/nextMarketing/wxapp/package/_975688610_1/app-service.js" done.
Decompile ./pages/authorization/authorization.wxml...
error on ./pages/authorization/authorization.wxml
err:  Error: Empty str in prop
    at wxmlify (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:179:47)
    at elemToString (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:233:57)
    at doWxml (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:250:33)
    at tryWxml (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:267:3)
    at z (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:311:23)
    at z (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuRestoreZ.js:216:17)
    at catchZ (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuRestoreZ.js:12:2)
    at getZ (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuRestoreZ.js:216:2)
    at wu.get.code (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:282:3)
    at ioLimit.runWithCb (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuLib.js:80:8)
Decompile ./pages/classdetail/classdetail.wxml...
error on ./pages/classdetail/classdetail.wxml
err:  TypeError: Cannot set property 'tag' of undefined
    at analyze (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:132:26)
    at anaRecursion (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:10:10)
    at analyze (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:43:10)
    at doWxml (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:248:2)
    at tryWxml (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:267:3)
    at z (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:311:23)
    at z (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuRestoreZ.js:216:17)
    at catchZ (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuRestoreZ.js:12:2)
    at getZ (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuRestoreZ.js:216:2)
    at wu.get.code (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:282:3)
Decompile ./pages/classes/classes.wxml...
error on ./pages/classes/classes.wxml
err:  Error: Empty str in prop
    at wxmlify (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:179:47)
    at elemToString (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:233:57)
    at doWxml (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:250:33)
    at tryWxml (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:267:3)
    at z (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:311:23)
    at z (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuRestoreZ.js:216:17)
    at catchZ (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuRestoreZ.js:12:2)
    at getZ (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuRestoreZ.js:216:2)
    at wu.get.code (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:282:3)
    at ioLimit.runWithCb (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuLib.js:80:8)
Decompile ./pages/index/index.wxml...
error on ./pages/index/index.wxml
err:  Error: Empty str in prop
    at wxmlify (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:179:47)
    at elemToString (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:233:57)
    at doWxml (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:250:33)
    at tryWxml (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:267:3)
    at z (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:311:23)
    at z (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuRestoreZ.js:216:17)
    at catchZ (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuRestoreZ.js:12:2)
    at getZ (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuRestoreZ.js:216:2)
    at wu.get.code (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:282:3)
    at ioLimit.runWithCb (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuLib.js:80:8)
Decompile ./pages/logs/logs.wxml...
error on ./pages/logs/logs.wxml
err:  Error: Empty str in prop
    at wxmlify (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:179:47)
    at elemToString (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:233:57)
    at doWxml (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:250:33)
    at tryWxml (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:267:3)
    at z (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:311:23)
    at z (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuRestoreZ.js:216:17)
    at catchZ (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuRestoreZ.js:12:2)
    at getZ (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuRestoreZ.js:216:2)
    at wu.get.code (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:282:3)
    at ioLimit.runWithCb (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuLib.js:80:8)
Decompile ./pages/mine/mine.wxml...
error on ./pages/mine/mine.wxml
err:  Error: Empty str in prop
    at wxmlify (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:179:47)
    at elemToString (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:233:57)
    at elemRecursion (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:190:10)
    at elemToString (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:224:12)
    at doWxml (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:250:33)
    at tryWxml (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:267:3)
    at z (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:311:23)
    at z (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuRestoreZ.js:216:17)
    at catchZ (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuRestoreZ.js:12:2)
    at getZ (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuRestoreZ.js:216:2)
Decompile ./pages/noticedetail/noticedetail.wxml...
error on ./pages/noticedetail/noticedetail.wxml
err:  Error: Empty str in prop
    at wxmlify (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:179:47)
    at elemToString (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:233:57)
    at doWxml (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:250:33)
    at tryWxml (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:267:3)
    at z (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:311:23)
    at z (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuRestoreZ.js:216:17)
    at catchZ (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuRestoreZ.js:12:2)
    at getZ (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuRestoreZ.js:216:2)
    at wu.get.code (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:282:3)
    at ioLimit.runWithCb (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuLib.js:80:8)
Decompile ./pages/publishtask/publishtask.wxml...
error on ./pages/publishtask/publishtask.wxml
err:  Error: Empty str in prop
    at wxmlify (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:179:47)
    at elemToString (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:233:57)
    at doWxml (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:250:33)
    at tryWxml (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:267:3)
    at z (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:311:23)
    at z (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuRestoreZ.js:216:17)
    at catchZ (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuRestoreZ.js:12:2)
    at getZ (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuRestoreZ.js:216:2)
    at wu.get.code (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:282:3)
    at ioLimit.runWithCb (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuLib.js:80:8)
Decompile ./pages/registered/registered.wxml...
error on ./pages/registered/registered.wxml
err:  Error: Empty str in prop
    at wxmlify (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:179:47)
    at elemToString (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:233:57)
    at doWxml (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:250:33)
    at tryWxml (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:267:3)
    at z (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:311:23)
    at z (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuRestoreZ.js:216:17)
    at catchZ (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuRestoreZ.js:12:2)
    at getZ (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuRestoreZ.js:216:2)
    at wu.get.code (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:282:3)
    at ioLimit.runWithCb (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuLib.js:80:8)
Decompile ./pages/studentdetail/studentdetail.wxml...
error on ./pages/studentdetail/studentdetail.wxml
err:  Error: Empty str in prop
    at wxmlify (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:179:47)
    at elemToString (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:233:57)
    at doWxml (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:250:33)
    at tryWxml (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:267:3)
    at z (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:311:23)
    at z (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuRestoreZ.js:216:17)
    at catchZ (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuRestoreZ.js:12:2)
    at getZ (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuRestoreZ.js:216:2)
    at wu.get.code (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:282:3)
    at ioLimit.runWithCb (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuLib.js:80:8)
Decompile ./pages/students/students.wxml...
error on ./pages/students/students.wxml
err:  TypeError: Cannot set property 'tag' of undefined
    at analyze (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:132:26)
    at anaRecursion (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:10:10)
    at analyze (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:43:10)
    at doWxml (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:248:2)
    at tryWxml (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:267:3)
    at z (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:311:23)
    at z (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuRestoreZ.js:216:17)
    at catchZ (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuRestoreZ.js:12:2)
    at getZ (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuRestoreZ.js:216:2)
    at wu.get.code (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:282:3)
Decompile ./pages/task/task.wxml...
error on ./pages/task/task.wxml
err:  Error: Empty str in prop
    at wxmlify (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:179:47)
    at elemToString (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:233:57)
    at doWxml (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:250:33)
    at tryWxml (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:267:3)
    at z (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:311:23)
    at z (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuRestoreZ.js:216:17)
    at catchZ (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuRestoreZ.js:12:2)
    at getZ (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuRestoreZ.js:216:2)
    at wu.get.code (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:282:3)
    at ioLimit.runWithCb (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuLib.js:80:8)
Decompile ./pages/taskcomment/taskcomment.wxml...
error on ./pages/taskcomment/taskcomment.wxml
err:  Error: Empty str in prop
    at wxmlify (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:179:47)
    at elemToString (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:233:57)
    at doWxml (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:250:33)
    at tryWxml (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:267:3)
    at z (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:311:23)
    at z (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuRestoreZ.js:216:17)
    at catchZ (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuRestoreZ.js:12:2)
    at getZ (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuRestoreZ.js:216:2)
    at wu.get.code (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:282:3)
    at ioLimit.runWithCb (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuLib.js:80:8)
Decompile ./pages/taskread/taskread.wxml...
error on ./pages/taskread/taskread.wxml
err:  Error: Empty str in prop
    at wxmlify (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:179:47)
    at elemToString (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:233:57)
    at doWxml (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:250:33)
    at tryWxml (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:267:3)
    at z (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:311:23)
    at z (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuRestoreZ.js:216:17)
    at catchZ (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuRestoreZ.js:12:2)
    at getZ (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuRestoreZ.js:216:2)
    at wu.get.code (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:282:3)
    at ioLimit.runWithCb (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuLib.js:80:8)
Decompile ./pages/taskreaddetail/taskreaddetail.wxml...
error on ./pages/taskreaddetail/taskreaddetail.wxml
err:  Error: Empty str in prop
    at wxmlify (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:179:47)
    at elemToString (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:233:57)
    at doWxml (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:250:33)
    at tryWxml (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:267:3)
    at z (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:311:23)
    at z (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuRestoreZ.js:216:17)
    at catchZ (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuRestoreZ.js:12:2)
    at getZ (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuRestoreZ.js:216:2)
    at wu.get.code (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:282:3)
    at ioLimit.runWithCb (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuLib.js:80:8)
Decompile ./pages/tasks/tasks.wxml...
error on ./pages/tasks/tasks.wxml
err:  Error: Empty str in prop
    at wxmlify (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:179:47)
    at elemToString (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:233:57)
    at elemRecursion (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:190:10)
    at elemToString (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:224:12)
    at doWxml (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:250:33)
    at tryWxml (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:267:3)
    at z (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:311:23)
    at z (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuRestoreZ.js:216:17)
    at catchZ (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuRestoreZ.js:12:2)
    at getZ (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuRestoreZ.js:216:2)
Decompile ./pages/terms_of_service/terms_of_service.wxml...
error on ./pages/terms_of_service/terms_of_service.wxml
err:  Error: Empty str in prop
    at wxmlify (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:179:47)
    at elemToString (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:233:57)
    at doWxml (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:250:33)
    at tryWxml (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:267:3)
    at z (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:311:23)
    at z (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuRestoreZ.js:216:17)
    at catchZ (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuRestoreZ.js:12:2)
    at getZ (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuRestoreZ.js:216:2)
    at wu.get.code (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxml.js:282:3)
    at ioLimit.runWithCb (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuLib.js:80:8)

/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/node_modules/vm2/lib/main.js:218
                        throw this._internal.Decontextify.value(e);
                        ^
ReferenceError: _C is not defined
    at vm.js:2:1
    at Script.runInContext (vm.js:74:29)
    at VM.run (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/node_modules/vm2/lib/main.js:212:72)
    at wu.get.code (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuWxss.js:160:16)
    at ioLimit.runWithCb (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuLib.js:80:8)
    at agent (/Users/machero/Desktop/nextMarketing/wxapp/wxappUnpacker/wuLib.js:54:14)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:532:3
```

**Comment by qwerty472123** [comment]
请阅读完issue_template并按要求发帖
你这样我无法分析
