### ISSUE TITLE
解析小程序中途失败

### ISSUE THREAD

**Issue by yuchuanxi** [qwerty472123/wxappUnpacker#91]
程序执行命令(可选):
```
node wuWxapkg.js ../testWx/_-482450903_7.wxapkg ../testWx
```

程序执行错误信息(如果反馈是抛出异常的错误，必填):

```
Unpack file ../testWx...
/Users/tudou/Coding/wxappUnpacker/wuLib.js:79
		if(err)throw Error("Read file error: "+err);
		       ^

Error: Read file error: Error: EISDIR: illegal operation on a directory, read
    at ioLimit.runWithCb (/Users/tudou/Coding/wxappUnpacker/wuLib.js:79:16)
    at agent (/Users/tudou/Coding/wxappUnpacker/wuLib.js:54:14)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:495:12)
```

程序包(你所要解压的程序包地址, 可为网盘链接, 也可直接上传[上传前请先打包]. 必填):
[_-482450903_7.wxapkg.zip](https://github.com/qwerty472123/wxappUnpacker/files/2123048/_-482450903_7.wxapkg.zip)

其他附加内容:

**Comment by qwerty472123** [comment]
看了readme再来好吗？
执行命令应该是node wuWxapkg.js ../testWx/_-482450903_7.wxapkg
输出目录是程序自动创建的，要自己选请手工改代码
